import type { RestaurantSeed } from "./restaurants";

// ── Denver restaurant data (13 restaurants) ──────────────────────────────────

export function getDenverRestaurants(): RestaurantSeed[] {
  return [
    // ═══ TIER 1: 100% Dedicated Facilities (2) ═══
    {
      name: "Just BE Kitchen",
      address: "2364 15th St, Denver, CO 80202",
      cuisine_type: "Gluten-Free & Paleo",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "fish", "gluten", "peanuts", "sesame", "shellfish", "soy", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "soy", "eggs", "nuts"],
      description: "Denver's first 100% gluten-free, grain-free, and soy-free restaurant. Entire kitchen is dedicated paleo-friendly — no gluten, dairy, soy, or refined sugar on premises. Celiac-safe comfort food.",
      website: "https://justbekitchen.com",
      phone: "(303) 284-6176",
      image_url: "",
      verified: true,
    },
    {
      name: "Rivers and Roads Coffee",
      address: "2539 Bruce Randolph Ave, Denver, CO 80205",
      cuisine_type: "Gluten-Free Cafe & Bakery",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["fish", "gluten", "peanuts", "sesame", "soy", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "eggs", "nuts"],
      description: "Clayton neighborhood cafe with an entirely gluten-free kitchen. Pastries, breakfast burritos, sandwiches, and coffee — all prepared in a 100% dedicated gluten-free facility. Celiac-safe.",
      website: "https://riversandroadscoffee.com",
      phone: "(720) 810-2877",
      image_url: "",
      verified: true,
    },

    // ═══ TIER 2: Certified Allergen Protocols (4) ═══
    {
      name: "True Food Kitchen",
      address: "2800 E 2nd Ave, Denver, CO 80206",
      cuisine_type: "Health-Conscious American",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["eggs", "gluten", "peanuts", "fish"],
      allergens_handled: ["gluten", "dairy", "soy", "peanuts", "tree nuts", "shellfish"],
      description: "Cherry Creek location of the seasonal health-driven chain. Detailed allergen matrix with trained staff on all major allergens. Kitchen follows strict cross-contact protocols for modified dishes.",
      website: "https://truefoodkitchen.com",
      phone: "(720) 772-2745",
      image_url: "",
      verified: true,
    },
    {
      name: "Root Down",
      address: "1600 W 33rd Ave, Denver, CO 80211",
      cuisine_type: "Farm-to-Table Global",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "soy", "peanuts", "eggs"],
      allergens_handled: ["gluten", "dairy", "soy", "peanuts", "tree nuts", "eggs"],
      description: "Highlands neighborhood staple in a converted gas station with strong allergen protocols. Dedicated gluten-free fryer, separate prep areas, and a kitchen well-versed in navigating dietary restrictions.",
      website: "https://rootdowndenver.com",
      phone: "(303) 993-4200",
      image_url: "",
      verified: true,
    },
    {
      name: "City O' City",
      address: "206 E 13th Ave, Denver, CO 80203",
      cuisine_type: "Vegetarian & Vegan",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy", "peanuts", "eggs"],
      allergens_handled: ["gluten", "soy", "nuts", "eggs"],
      description: "Capitol Hill's beloved vegetarian restaurant with a dedicated gluten-free fryer. Allergen-aware kitchen with clearly marked gluten-free, soy-free, and nut-free options. Vegan and gluten-free comfort food.",
      website: "https://cityocitydenver.com",
      phone: "(303) 831-6443",
      image_url: "",
      verified: true,
    },
    {
      name: "Linger",
      address: "2030 W 30th Ave, Denver, CO 80211",
      cuisine_type: "Global Small Plates",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "soy", "nuts", "shellfish"],
      description: "LoHi hotspot in a former mortuary with rooftop views. Sister restaurant to Root Down sharing the same strong allergen protocols. Dedicated fryer and clear allergen labeling on the globally-inspired menu.",
      website: "https://lingereats.com",
      phone: "(303) 993-3120",
      image_url: "",
      verified: true,
    },

    // ═══ TIER 3: Dietary-Friendly (7) ═══
    {
      name: "Snooze an A.M. Eatery",
      address: "2262 Larimer St, Denver, CO 80205",
      cuisine_type: "Brunch & Breakfast",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["dairy", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy"],
      description: "Denver-born brunch institution with multiple locations. Gluten-free pancakes and toast available. Allergen guide on request; kitchen can modify most dishes. Busy weekends — expect longer prep for allergy orders.",
      website: "https://snoozeeatery.com",
      phone: "(303) 297-0700",
      image_url: "",
      verified: true,
    },
    {
      name: "The Cherry Cricket",
      address: "2641 E 2nd Ave, Denver, CO 80206",
      cuisine_type: "Burgers",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Cherry Creek's legendary burger joint since 1945. Gluten-free buns and lettuce wraps available. Shared fryers — fries not safe for celiac diners. Best for dairy or egg concerns.",
      website: "https://cherrycricket.com",
      phone: "(303) 322-7666",
      image_url: "",
      verified: true,
    },
    {
      name: "Denver Biscuit Company",
      address: "3237 E Colfax Ave, Denver, CO 80206",
      cuisine_type: "Southern Biscuits & Brunch",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "soy"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Massive biscuit sandwiches that anchor the Atomic Cowboy bar. Entire concept built around wheat flour — no gluten-free biscuits available. Best for dairy or egg sensitivities only.",
      website: "https://denbisco.com",
      phone: "(303) 377-7900",
      image_url: "",
      verified: true,
    },
    {
      name: "Illegal Pete's",
      address: "1744 E Evans Ave, Denver, CO 80210",
      cuisine_type: "Mission-Style Burritos",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["shellfish", "soy"],
      allergens_handled: ["gluten", "dairy"],
      description: "Colorado-born burrito chain with a DU campus location. Gluten-free bowls available by skipping the tortilla. Flour tortillas dominate the kitchen — celiac diners should be cautious of cross-contact.",
      website: "https://illegalpetes.com",
      phone: "(303) 733-0012",
      image_url: "",
      verified: true,
    },
    {
      name: "Work & Class",
      address: "2500 Larimer St, Denver, CO 80205",
      cuisine_type: "Latin American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "shellfish"],
      allergens_handled: ["gluten", "dairy", "nuts", "eggs"],
      description: "RiNo's counter-service Latin American gem. Menu clearly marks gluten-free items. Small kitchen with strong allergen awareness — staff can guide dietary choices but cross-contact risk exists.",
      website: "https://workandclassdenver.com",
      phone: "(303) 292-0700",
      image_url: "",
      verified: true,
    },
    {
      name: "Avanti F&B",
      address: "3200 Pecos St, Denver, CO 80211",
      cuisine_type: "Food Hall",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "shellfish"],
      allergens_handled: ["gluten", "dairy", "soy", "nuts", "shellfish"],
      description: "LoHi food hall with 7 rotating restaurant concepts and skyline views. Individual vendors handle allergens differently — ask each stall. Shared seating and varied safety protocols.",
      website: "https://avantifandb.com",
      phone: "(720) 269-4778",
      image_url: "",
      verified: true,
    },
    {
      name: "Sam's No. 3",
      address: "1500 Curtis St, Denver, CO 80202",
      cuisine_type: "Diner",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "shellfish"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy"],
      description: "Downtown Denver diner institution since 1927 with a massive menu. Gluten-free options and modifications available. High-volume kitchen — best for mild sensitivities. Inform server of allergies.",
      website: "https://samsno3.com",
      phone: "(303) 534-1927",
      image_url: "",
      verified: true,
    },

    // ═══ AUTO-DISCOVERED (Tier 2-3 via Google Places) ═══
{
      name: "Corinne Denver",
      address: "1455 California St, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Copper Table",
      address: "6700 N Gaylord Rockies Blvd, Aurora, CO 80019",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Alma Fonda Fina",
      address: "2556 15th St, Denver, CO 80211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Culinary Dropout",
      address: "4141 E 9th Ave, Denver, CO 80220",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Mercantile",
      address: "1701 Wynkoop St #155, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Salt Water Social",
      address: "201 Columbine St, Denver, CO 80206",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Buckhorn Exchange",
      address: "1000 Osage St, Denver, CO 80204",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Wildflower",
      address: "3638 Navajo St, Denver, CO 80211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Guard and Grace",
      address: "1801 California St, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Bindery",
      address: "1817 Central St, Denver, CO 80211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Tavernetta",
      address: "1889 16th St Mall, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "El Five",
      address: "2930 Umatilla St Unit #500, Denver, CO 80211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Velvet Cellar",
      address: "1500 Wynkoop St #101, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "major tom",
      address: "2845 Larimer St, Denver, CO 80205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Fox And The Hen",
      address: "2257 W 32nd Ave, Denver, CO 80211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "BurnDown",
      address: "476 S Broadway, Denver, CO 80209",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Dear Emilia",
      address: "3615 Delgany St, Denver, CO 80216",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Hampton Social - Denver",
      address: "2501 16th St, Denver, CO 80211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Pasque",
      address: "240 14th St, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Aquarium Restaurant",
      address: "700 Water St, Denver, CO 80211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Fire Restaurant & Lounge",
      address: "1201 Broadway, Denver, CO 80203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Stellar Jay",
      address: "240 14th St, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Pig & The Sprout",
      address: "1900 Chestnut Pl, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Restaurant Olivia",
      address: "290 S Downing St, Denver, CO 80209",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Rioja",
      address: "1431 Larimer St, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Plimoth",
      address: "2335 E 28th Ave, Denver, CO 80205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "EDGE Restaurant & Bar",
      address: "1111 14th St, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Rabbit Hole",
      address: "101 N Tejon St, Colorado Springs, CO 80903",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Point Easy Denver",
      address: "2000 E 28th Ave, Denver, CO 80205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Steuben's Uptown",
      address: "523 E 17th Ave, Denver, CO 80203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Table 6",
      address: "609 Corona St, Denver, CO 80218",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Ocean Prime",
      address: "1465 Larimer St, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "STK Steakhouse Denver",
      address: "1550 Market St, Denver, CO 80202",
      cuisine_type: "Steakhouse",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","eggs"],
      description: "Auto-discovered via Google Places. A steakhouse restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Mezcaleria Alma",
      address: "2550 15th St, Denver, CO 80211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Senor Bear",
      address: "3301 Tejon St, Denver, CO 80211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Potager",
      address: "1109 N Ogden St, Denver, CO 80218",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Casa Bonita",
      address: "6715 W Colfax Ave, Lakewood, CO 80214",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Mimosas",
      address: "2752 Welton St, Denver, CO 80205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Ajax Downtown",
      address: "1899 16th St Mall, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Stout Street Social",
      address: "1400 Stout St, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Bar Dough",
      address: "2227 W 32nd Ave, Denver, CO 80211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Acova",
      address: "3651 Navajo St, Denver, CO 80211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Panzano",
      address: "909 17th St, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "West Saloon & Kitchen",
      address: "501 16th St Mall, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Ash'Kara",
      address: "2005 W 33rd Ave, Denver, CO 80211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Tom's Watch Bar - Coors Field",
      address: "1601 19th St Unit 100, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Tupelo Honey Southern Kitchen & Bar",
      address: "1650 Wewatta St #104, Denver, CO 80202",
      cuisine_type: "Southern",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A southern restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Yard House",
      address: "1555 Court Pl, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Flight Club Denver",
      address: "1959 16th St, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Champagne Tiger",
      address: "601 E Colfax Ave, Denver, CO 80203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Rhein Haus Denver",
      address: "1415 Market St, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Tamayo by Chef Richard Sandoval",
      address: "1400 Larimer St, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Bird",
      address: "1529 S Pearl St, Denver, CO 80210",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Jovanina's Broken Italian",
      address: "1520 Blake St, Denver, CO 80202",
      cuisine_type: "Italian",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy","eggs"],
      description: "Auto-discovered via Google Places. A italian restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Watercourse Foods",
      address: "837 E 17th Ave, Denver, CO 80218",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "el Camino",
      address: "3628 W 32nd Ave, Denver, CO 80211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Ace Eat Serve",
      address: "501 E 17th Ave, Denver, CO 80203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Dulce Vida",
      address: "1201 Cherokee St, Denver, CO 80204",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "La Diabla Pozole y Mezcal",
      address: "2233 Larimer St, Denver, CO 80205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Homegrown Tap & Dough",
      address: "1001 S Gaylord St, Denver, CO 80209",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Izakaya Den",
      address: "1487A S Pearl St, Denver, CO 80210",
      cuisine_type: "Japanese",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A japanese restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Corsica Wine Bar",
      address: "2801 Walnut St Ste 100, Denver, CO 80205",
      cuisine_type: "Wine Bar",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A wine bar restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Fish N Beer",
      address: "3510 Larimer St, Denver, CO 80205",
      cuisine_type: "Seafood",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","shellfish"],
      description: "Auto-discovered via Google Places. A seafood restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Leven Deli Co.",
      address: "123 W 12th Ave, Denver, CO 80204",
      cuisine_type: "Deli & Sandwiches",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A deli & sandwiches restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Snooze, an A.M. Eatery",
      address: "2262 Larimer St, Denver, CO 80205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Water Grill Denver",
      address: "1691 Market St, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Capital Grille",
      address: "1450 Larimer St, Denver, CO 80202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "JINYA Ramen Bar - Union Station",
      address: "1710 Wynkoop St, Denver, CO 80202",
      cuisine_type: "Japanese",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A japanese restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Jacks on Pearl",
      address: "1475 S Pearl St, Denver, CO 80210",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Beckon",
      address: "2843 Larimer St, Denver, CO 80205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Denver. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
  ];
}
