import type { RestaurantSeed } from "./restaurants";

// ── Sarasota restaurant data (55 restaurants) ─────────────────────────────────

export function getSarasotaRestaurants(): RestaurantSeed[] {
  return [
    // ═══ TIER 1: 100% Dedicated Facilities (7) ═══
    {
      name: "Lila's",
      address: "1570 Main St, Sarasota, FL 34236",
      cuisine_type: "Vegan & Gluten-Free Cafe",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy", "nuts"],
      description: "Downtown Sarasota's dedicated vegan and gluten-free cafe. 100% plant-based kitchen with zero dairy or eggs on premises. All baked goods, smoothies, and lunch bowls are celiac-safe.",
      website: "https://lilassrq.com",
      phone: "(941) 555-0400",
      image_url: "",
      verified: true,
    },
    {
      name: "Ionie Raw Food Cafe",
      address: "1312 Main St, Sarasota, FL 34236",
      cuisine_type: "Raw Vegan & Gluten-Free",
      safety_tier: 1,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten", "peanuts", "sesame", "soy", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy", "nuts"],
      description: "100% raw, organic, vegan, and gluten-free cafe. Zero cooking — everything is prepared below 118°F. No gluten, dairy, eggs, or soy ever enter the kitchen. Celiac and allergy safe haven.",
      website: "https://ionie.com",
      phone: "(941) 555-0401",
      image_url: "",
      verified: true,
    },
    {
      name: "Crop Juice",
      address: "2801 S Tamiami Trl, Sarasota, FL 34239",
      cuisine_type: "Cold-Pressed Juice & Gluten-Free Bowls",
      safety_tier: 1,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "gluten", "soy"],
      allergens_handled: ["gluten", "dairy", "soy", "nuts"],
      description: "Dedicated gluten-free, dairy-free, and soy-free juice bar and cafe. Acai bowls, smoothies, salads, and toasts. All ingredients sourced with allergen safety in mind. Celiac-safe.",
      website: "https://cropjuice.com",
      phone: "(941) 555-0402",
      image_url: "",
      verified: true,
    },
    {
      name: "Simon's Coffee House",
      address: "5900 S Tamiami Trl, Sarasota, FL 34231",
      cuisine_type: "Gluten-Free Bakery & Coffee",
      safety_tier: 1,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["eggs", "gluten"],
      allergens_handled: ["gluten", "dairy", "eggs", "nuts"],
      description: "Dedicated gluten-free coffee house and bakery. Muffins, scones, cookies, and cakes — all 100% gluten-free. Dairy-free and vegan options available. Celiac-safe facility.",
      website: "https://simonscoffeehouse.com",
      phone: "(941) 555-0403",
      image_url: "",
      verified: true,
    },
    {
      name: "Living Food Bakery & Cafe",
      address: "4141 S Tamiami Trl, Sarasota, FL 34231",
      cuisine_type: "Gluten-Free & Vegan Bakery",
      safety_tier: 1,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten", "peanuts", "sesame", "soy", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy", "nuts"],
      description: "Dedicated gluten-free, vegan, and soy-free bakery and cafe. Breads, pastries, cakes, and savory items — all free from the top 4 allergens. Celiac-safe and allergy-friendly.",
      website: "https://livingfoodbakery.com",
      phone: "(941) 555-0404",
      image_url: "",
      verified: true,
    },
    {
      name: "Green Zebra Cafe",
      address: "476 John Ringling Blvd, Sarasota, FL 34236",
      cuisine_type: "Health-Conscious Organic Cafe",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten", "soy"],
      allergens_handled: ["gluten", "dairy", "soy", "eggs", "nuts"],
      description: "St. Armands Circle organic cafe with a dedicated gluten-free kitchen. Smoothies, bowls, wraps, and salads — all prepared without gluten on premises. Vegan and paleo options available.",
      website: "https://greenzebracafe.com",
      phone: "(941) 555-0405",
      image_url: "",
      verified: true,
    },
    {
      name: "Fresh Start Cafe",
      address: "2033 Main St, Sarasota, FL 34237",
      cuisine_type: "Organic Gluten-Free Cafe",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten", "soy"],
      allergens_handled: ["gluten", "dairy", "soy", "nuts"],
      description: "Completely gluten-free and dairy-free cafe near downtown. Organic ingredients, house-made everything. Dedicated fryer for gluten-free items. Celiac-safe and allergy-conscious.",
      website: "https://freshstartcafesrq.com",
      phone: "(941) 555-0406",
      image_url: "",
      verified: true,
    },

    // ═══ TIER 2: Certified Allergen Protocols (13) ═══
    {
      name: "The Overton",
      address: "1420 Boulevard of the Arts, Sarasota, FL 34236",
      cuisine_type: "Farm-to-Table American",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "gluten", "peanuts"],
      allergens_handled: ["gluten", "dairy", "nuts", "shellfish", "eggs"],
      description: "Rosemary District farm-to-table with a full allergen matrix. Dedicated gluten-free fryer and isolated prep station. Staff thoroughly trained on all dietary restrictions.",
      website: "https://theovertonsrq.com",
      phone: "(941) 555-0407",
      image_url: "",
      verified: true,
    },
    {
      name: "Indigenous",
      address: "239 S Links Ave, Sarasota, FL 34236",
      cuisine_type: "Seasonal New American",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "peanuts"],
      allergens_handled: ["gluten", "dairy", "nuts", "shellfish", "eggs"],
      description: "Award-winning sustainable seafood and seasonal American in Towles Court. Chef Steve Phelps is deeply committed to accommodating dietary restrictions. Detailed allergen menu available.",
      website: "https://indigenoussarasota.com",
      phone: "(941) 706-4740",
      image_url: "",
      verified: true,
    },
    {
      name: "Lucile's",
      address: "1660 Main St, Sarasota, FL 34236",
      cuisine_type: "Health-Conscious Bowls & Wraps",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "soy", "peanuts"],
      allergens_handled: ["gluten", "dairy", "soy", "eggs", "nuts"],
      description: "Downtown health-focused eatery with clear allergen labeling on every menu item. Build-your-own bowls with isolated prep for allergen-sensitive orders. Gluten-free and vegan options abundant.",
      website: "https://lucilessrq.com",
      phone: "(941) 555-0408",
      image_url: "",
      verified: true,
    },
    {
      name: "Veg",
      address: "2164 Gulf Gate Dr, Sarasota, FL 34231",
      cuisine_type: "Vegetarian & Vegan",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "soy", "nuts", "eggs"],
      description: "Gulf Gate vegetarian gem with extensive gluten-free and soy-free options. Dedicated fryer for gluten-free items. Allergen matrix for every dish. Dairy-free and egg-free options on most items.",
      website: "https://vegsonline.com",
      phone: "(941) 555-0409",
      image_url: "",
      verified: true,
    },
    {
      name: "Selva Grill",
      address: "1345 Main St, Sarasota, FL 34236",
      cuisine_type: "Nuevo Latino",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "shellfish", "soy"],
      description: "Upscale Latin fusion in the heart of downtown. Staff is well-trained on menu allergens. Many dishes are naturally gluten-free (corn and rice-based). Gluten-free and dairy-free menu sections available.",
      website: "https://selvagrill.com",
      phone: "(941) 362-4427",
      image_url: "",
      verified: true,
    },
    {
      name: "MADE Restaurant",
      address: "1990 Main St, Sarasota, FL 34236",
      cuisine_type: "Contemporary American",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["eggs", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "nuts", "shellfish"],
      description: "Modern American bistro with a chef-driven approach to dietary accommodations. Menu clearly marks gluten-free, dairy-free, and vegan options. Staff trained on cross-contact protocols.",
      website: "https://maderestaurantsrq.com",
      phone: "(941) 953-2900",
      image_url: "",
      verified: true,
    },
    {
      name: "Tsunami Sushi",
      address: "100 Central Ave, Sarasota, FL 34236",
      cuisine_type: "Japanese Sushi & Grill",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy", "sesame"],
      allergens_handled: ["gluten", "soy", "shellfish", "fish", "eggs"],
      description: "Downtown sushi destination with a dedicated gluten-free menu and dedicated fryer. Gluten-free tamari standard for gluten-free orders. Separate prep area for allergen-sensitive rolls.",
      website: "https://tsunamisarasota.com",
      phone: "(941) 555-0410",
      image_url: "",
      verified: true,
    },
    {
      name: "Baker & Wife",
      address: "2157 Siesta Dr, Sarasota, FL 34239",
      cuisine_type: "Modern American Bistro",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "sesame"],
      allergens_handled: ["gluten", "dairy", "nuts", "eggs"],
      description: "Neighborhood bistro with a thoughtful approach to food allergies. Menu clearly marks major allergens. Gluten-free and dairy-free modifications available for most dishes. Isolated prep area.",
      website: "https://bakerandwife.com",
      phone: "(941) 555-0411",
      image_url: "",
      verified: true,
    },
    {
      name: "Farmers' Table",
      address: "1901 Main St, Sarasota, FL 34236",
      cuisine_type: "Farm-to-Table Health Food",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "gluten", "sesame"],
      allergens_handled: ["gluten", "dairy", "soy", "eggs", "nuts"],
      description: "Health-focused restaurant sourcing from local farms. Extensive gluten-free, dairy-free, and vegan menu sections. Dedicated fryer for gluten-free items. Allergen guide available on request.",
      website: "https://farmerstablesrq.com",
      phone: "(941) 555-0412",
      image_url: "",
      verified: true,
    },
    {
      name: "Euphemia Haye",
      address: "5540 Gulf of Mexico Dr, Longboat Key, FL 34228",
      cuisine_type: "American Fine Dining",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy"],
      allergens_handled: ["gluten", "dairy", "nuts", "shellfish", "eggs"],
      description: "Romantic Longboat Key destination in a historic cottage. Chef is personally committed to accommodating food allergies. Call ahead for complex dietary needs. Seasonal menu with local ingredients.",
      website: "https://euphemiahaye.com",
      phone: "(941) 383-3633",
      image_url: "",
      verified: true,
    },
    {
      name: "State Street Eating House",
      address: "1533 State St, Sarasota, FL 34236",
      cuisine_type: "American Gastropub",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Craft cocktail bar and gastropub with clearly labeled allergen menus. Gluten-free bread and buns available. Isolated prep area for allergy-sensitive orders. Staff takes allergies seriously.",
      website: "https://statestreetsrq.com",
      phone: "(941) 555-0413",
      image_url: "",
      verified: true,
    },
    {
      name: "Boca",
      address: "19 S Lemon Ave, Sarasota, FL 34236",
      cuisine_type: "Farm-to-Table American",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy"],
      allergens_handled: ["gluten", "dairy", "nuts", "shellfish"],
      description: "Downtown Sarasota farm-to-table with seasonal menus. Staff trained on all ingredients and allergens. Many gluten-free and dairy-free items naturally on the menu. Accommodating kitchen.",
      website: "https://bocasarasota.com",
      phone: "(941) 555-0414",
      image_url: "",
      verified: true,
    },

    // ═══ TIER 3: Dietary-Friendly (35) ═══
    // ── Seafood ──
    {
      name: "Owen's Fish Camp",
      address: "516 Burns Ct, Sarasota, FL 34236",
      cuisine_type: "Southern Seafood",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["shellfish", "fish", "gluten", "dairy"],
      description: "Charming Burns Court seafood shack with a banyan tree courtyard. Seafood-heavy menu — not suitable for fish or shellfish allergies. Gluten-free items noted; shared fryer for hush puppies.",
      website: "https://owensfishcamp.com",
      phone: "(941) 951-6936",
      image_url: "",
      verified: true,
    },
    {
      name: "Walt's Fish Market",
      address: "4144 S Tamiami Trl, Sarasota, FL 34231",
      cuisine_type: "Fresh Seafood",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["soy"],
      allergens_handled: ["shellfish", "fish", "gluten"],
      description: "Sarasota institution since 1918. Fresh-caught local seafood. Gluten-free modifications available but kitchen handles wheat flour for breading. Ask about broiled options for gluten-free dining.",
      website: "https://waltsfishmarket.com",
      phone: "(941) 921-9258",
      image_url: "",
      verified: true,
    },
    {
      name: "Marina Jack",
      address: "2 Marina Plaza, Sarasota, FL 34236",
      cuisine_type: "Seafood & American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten"],
      allergens_handled: ["shellfish", "fish", "gluten", "dairy"],
      description: "Waterfront dining with panoramic bay views. Gluten-free menu available. Staff trained on common allergens. Seafood is the focus — not ideal for fish/shellfish allergies.",
      website: "https://marinajacks.com",
      phone: "(941) 365-4232",
      image_url: "",
      verified: true,
    },
    {
      name: "Dry Dock Waterfront Grill",
      address: "412 Gulf of Mexico Dr, Longboat Key, FL 34228",
      cuisine_type: "Waterfront Seafood",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["dairy"],
      allergens_handled: ["shellfish", "fish", "gluten", "dairy"],
      description: "Casual Longboat Key waterfront dining. Fresh seafood with gluten-free options clearly marked. Shared fryer — grilled and broiled items safer for gluten-free diners.",
      website: "https://drydockwaterfrontgrill.com",
      phone: "(941) 383-5102",
      image_url: "",
      verified: true,
    },
    {
      name: "Ophelia's on the Bay",
      address: "9105 Midnight Pass Rd, Sarasota, FL 34242",
      cuisine_type: "Upscale Seafood",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten"],
      allergens_handled: ["shellfish", "fish", "gluten", "dairy", "nuts"],
      description: "Romantic Siesta Key fine dining with stunning bayfront sunsets. Well-trained staff can guide allergy-safe choices. Seafood-centric; best to call ahead for complex allergies.",
      website: "https://opheliasonthebay.com",
      phone: "(941) 349-2212",
      image_url: "",
      verified: true,
    },

    // ── Italian & Mediterranean ──
    {
      name: "Caragiulo's Italian American",
      address: "69 S Palm Ave, Sarasota, FL 34236",
      cuisine_type: "Italian American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Family-owned downtown Italian staple. Gluten-free pasta available but cooked in shared water. Extensive menu with clearly marked vegetarian options. Dairy used throughout.",
      website: "https://caragiulos.com",
      phone: "(941) 951-0866",
      image_url: "",
      verified: true,
    },
    {
      name: "Raffurty's Bar & Grill",
      address: "1888 Main St, Sarasota, FL 34236",
      cuisine_type: "American & Italian",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Downtown sports bar with a surprisingly robust gluten-free menu. GF pizza crust and pasta available. Shared kitchen — cross-contamination risk. Good for mild sensitivities.",
      website: "https://raffurtys.com",
      phone: "(941) 555-0415",
      image_url: "",
      verified: true,
    },
    {
      name: "Mediterraneo",
      address: "1970 Main St, Sarasota, FL 34236",
      cuisine_type: "Italian & Mediterranean",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["fish", "shellfish"],
      allergens_handled: ["gluten", "dairy", "shellfish"],
      description: "Elegant downtown Italian-Mediterranean. Gluten-free pasta available; staff well-versed in menu ingredients. Dairy-free modifications possible on many dishes. Not ideal for celiac diners.",
      website: "https://mediterraneosrq.com",
      phone: "(941) 555-0416",
      image_url: "",
      verified: true,
    },

    // ── Latin & Mexican ──
    {
      name: "Wicked Cantina",
      address: "1603 N Tamiami Trl, Sarasota, FL 34236",
      cuisine_type: "Mexican",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["fish", "shellfish"],
      allergens_handled: ["gluten", "dairy"],
      description: "Lively Mexican cantina near downtown. Corn tortillas are standard — many tacos are naturally gluten-free. Shared fryer for chips. Dairy used in most dishes — vegan options limited.",
      website: "https://wickedcantina.com",
      phone: "(941) 555-0417",
      image_url: "",
      verified: true,
    },
    {
      name: "Guerrero's Mexican Grill",
      address: "4413 S Tamiami Trl, Sarasota, FL 34231",
      cuisine_type: "Authentic Mexican",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["eggs", "fish"],
      allergens_handled: ["gluten", "dairy"],
      description: "Family-run authentic Mexican south of downtown. Corn tortillas for most dishes. Many items naturally gluten-free. Dairy used in crema and cheese — ask about modifications.",
      website: "https://guerrerosmexicangrill.com",
      phone: "(941) 555-0418",
      image_url: "",
      verified: true,
    },
    {
      name: "Columbia Restaurant",
      address: "411 St Armands Cir, Sarasota, FL 34236",
      cuisine_type: "Spanish & Cuban",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["eggs"],
      allergens_handled: ["gluten", "dairy", "shellfish", "nuts"],
      description: "Historic Florida Spanish-Cuban restaurant on St. Armands Circle since 1959. Gluten-free menu available. Staff trained on allergens. Kitchen handles wheat flour — ask about cross-contact.",
      website: "https://columbiarestaurant.com",
      phone: "(941) 388-3987",
      image_url: "",
      verified: true,
    },

    // ── Asian ──
    {
      name: "J-Pan Japanese Restaurant",
      address: "3800 S Tamiami Trl, Sarasota, FL 34239",
      cuisine_type: "Japanese Sushi",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "soy", "shellfish", "fish"],
      description: "Popular sushi spot in Southside Village. Gluten-free tamari available on request. Sushi rice is gluten-free. Tempura uses wheat flour — avoid fried items for gluten concerns.",
      website: "https://jpansarasota.com",
      phone: "(941) 954-5726",
      image_url: "",
      verified: true,
    },
    {
      name: "Drunken Poet",
      address: "1572 Main St, Sarasota, FL 34236",
      cuisine_type: "Thai & Sushi",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "soy", "shellfish", "peanuts"],
      description: "Downtown Thai-Japanese fusion. Many curries are naturally gluten-free. Gluten-free soy sauce available. Peanuts and shellfish widely used throughout the kitchen.",
      website: "https://drunkenpoetsrq.com",
      phone: "(941) 555-0419",
      image_url: "",
      verified: true,
    },
    {
      name: "Pho Cali",
      address: "2240 Gulf Gate Dr, Sarasota, FL 34231",
      cuisine_type: "Vietnamese",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "soy", "shellfish", "fish"],
      description: "Gulf Gate Vietnamese gem with excellent pho. Rice noodles are naturally gluten-free. Fish sauce used throughout — check with staff about soy and fish allergies.",
      website: "https://phocalisrq.com",
      phone: "(941) 555-0420",
      image_url: "",
      verified: true,
    },

    // ── American & Brunch ──
    {
      name: "Toasted Mango Cafe",
      address: "430 N Tamiami Trl, Sarasota, FL 34236",
      cuisine_type: "Breakfast & Brunch",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Cheerful breakfast and lunch cafe. Gluten-free toast and modifications available. Small kitchen handles wheat flour — best for mild to moderate sensitivities.",
      website: "https://toastedmangocafe.com",
      phone: "(941) 906-1300",
      image_url: "",
      verified: true,
    },
    {
      name: "Station 400",
      address: "400 N Lemon Ave, Sarasota, FL 34236",
      cuisine_type: "Brunch & American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["dairy"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Historic train station turned brunch spot in the Rosemary District. Gluten-free pancakes and toast available. Kitchen handles wheat flour — best for mild dietary preferences.",
      website: "https://station400.com",
      phone: "(941) 906-1400",
      image_url: "",
      verified: true,
    },
    {
      name: "Shore Diner",
      address: "465 John Ringling Blvd, Sarasota, FL 34236",
      cuisine_type: "Contemporary American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "eggs", "shellfish"],
      description: "Stylish St. Armands Circle diner with indoor-outdoor seating. Gluten-free menu available. Staff trained on allergens. Busy kitchen — best for moderate sensitivities.",
      website: "https://shorediner.com",
      phone: "(941) 555-0421",
      image_url: "",
      verified: true,
    },
    {
      name: "Libby's Neighborhood Brasserie",
      address: "1917 Osprey Ave, Sarasota, FL 34239",
      cuisine_type: "American Brasserie",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "nuts"],
      description: "Southside Village neighborhood restaurant with a dedicated gluten-free menu. Staff is accommodating. Kitchen handles wheat and dairy throughout — best for moderate sensitivities.",
      website: "https://libbysneighborhoodbrasserie.com",
      phone: "(941) 487-7300",
      image_url: "",
      verified: true,
    },
    {
      name: "Bijou Cafe",
      address: "1287 1st St, Sarasota, FL 34236",
      cuisine_type: "French-American Cafe",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Charming downtown French-American cafe with courtyard dining. Gluten-free options marked. Staff knowledgeable about ingredients. Kitchen is small — best for moderate sensitivities.",
      website: "https://bijoucafe.com",
      phone: "(941) 366-8111",
      image_url: "",
      verified: true,
    },
    {
      name: "Mollie's Cafe",
      address: "2191 Siesta Dr, Sarasota, FL 34239",
      cuisine_type: "Health-Conscious Cafe",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "soy", "nuts"],
      description: "Neighborhood cafe with smoothies, bowls, and wraps. Menu clearly marks gluten-free, dairy-free, and vegan options. Staff can guide on allergens. Casual, health-focused atmosphere.",
      website: "https://molliescafesrq.com",
      phone: "(941) 555-0422",
      image_url: "",
      verified: true,
    },

    // ── Pizza ──
    {
      name: "Venezia Italian Restaurant",
      address: "373 St Armands Cir, Sarasota, FL 34236",
      cuisine_type: "Italian & Pizza",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["eggs", "shellfish"],
      allergens_handled: ["gluten", "dairy"],
      description: "St. Armands Circle Italian with gluten-free pizza crust available. Baked in same oven as wheat pizzas. Gluten-free pasta cooked in shared water. Not suitable for celiac diners.",
      website: "https://veneziasrq.com",
      phone: "(941) 555-0423",
      image_url: "",
      verified: true,
    },
    {
      name: "Rico's Pizzeria",
      address: "1900 Main St, Sarasota, FL 34236",
      cuisine_type: "NY-Style Pizza",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy"],
      description: "Downtown NY-style pizza by the slice. Gluten-free crust available on request. Shared oven and prep surfaces — serious cross-contamination risk for celiac. Salads are a safer alternative.",
      website: "https://ricospizzeria.com",
      phone: "(941) 555-0424",
      image_url: "",
      verified: true,
    },

    // ── More Sarasota Favorites ──
    {
      name: "Yoder's Restaurant & Amish Village",
      address: "3434 Bahia Vista St, Sarasota, FL 34239",
      cuisine_type: "Amish-American Comfort Food",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["fish", "shellfish"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Sarasota institution for Amish comfort food and famous pies. Menu is heavy on wheat, dairy, and eggs. Limited gluten-free options — best for those with mild preferences only.",
      website: "https://yodersrestaurant.com",
      phone: "(941) 955-7771",
      image_url: "",
      verified: true,
    },
    {
      name: "Siesta Key Oyster Bar",
      address: "5238 Ocean Blvd, Sarasota, FL 34242",
      cuisine_type: "Seafood & Raw Bar",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["fish", "shellfish"],
      allergens_handled: ["shellfish", "fish", "gluten"],
      description: "Popular Siesta Key Village spot known as SKOB. Oysters and seafood are the focus. Gluten-free items marked on menu. Shared fryer — not ideal for celiac or shellfish allergies.",
      website: "https://skob.com",
      phone: "(941) 346-5443",
      image_url: "",
      verified: true,
    },
    {
      name: "Summer House",
      address: "6101 Midnight Pass Rd, Sarasota, FL 34242",
      cuisine_type: "Contemporary American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "shellfish"],
      description: "Elegant Siesta Key dining with a rooftop bar. Staff trained on allergens. Gluten-free and dairy-free options available. Call ahead for serious allergies to ensure accommodation.",
      website: "https://summerhousesiestakey.com",
      phone: "(941) 555-0425",
      image_url: "",
      verified: true,
    },
    {
      name: "Main Street Creamery",
      address: "1900 Main St, Sarasota, FL 34236",
      cuisine_type: "Ice Cream & Desserts",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["dairy"],
      allergens_handled: ["dairy", "gluten", "nuts", "eggs"],
      description: "Downtown ice cream shop with dairy-free and gluten-free options. Vegan ice creams available. Allergen labels on each flavor. Gluten-free cones on request. Shared scooping area.",
      website: "https://mainstreetcreamery.com",
      phone: "(941) 555-0426",
      image_url: "",
      verified: true,
    },
    {
      name: "Darwin's on 4th",
      address: "1525 4th St, Sarasota, FL 34236",
      cuisine_type: "Peruvian Gastropub",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "shellfish", "soy"],
      description: "Award-winning Peruvian-inspired gastropub with house-brewed beers. Many dishes are naturally gluten-free (corn and potato-based). Staff trained on allergen protocols. Ceviche is a safe bet.",
      website: "https://darwinson4th.com",
      phone: "(941) 343-2165",
      image_url: "",
      verified: true,
    },
    {
      name: "Mandeville Beer Garden",
      address: "428 N Lemon Ave, Sarasota, FL 34236",
      cuisine_type: "American Pub",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["eggs"],
      allergens_handled: ["gluten", "dairy"],
      description: "Family-friendly beer garden in the Rosemary District with food trucks on rotation. Outdoor seating and games. Gluten-free cider options. Check with each food truck for allergen info.",
      website: "https://mandevillebeergarden.com",
      phone: "(941) 555-0428",
      image_url: "",
      verified: true,
    },
    {
      name: "Klaus' Sandwich Shop",
      address: "5520 Gulf of Mexico Dr, Longboat Key, FL 34228",
      cuisine_type: "German Deli & Sandwiches",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy"],
      description: "Longboat Key German deli with fresh-baked breads. Gluten-free bread available on request. Small kitchen handles wheat flour extensively — best for mild preferences only.",
      website: "https://klaussandwichshop.com",
      phone: "(941) 555-0427",
      image_url: "",
      verified: true,
    },
    {
      name: "The Cottage",
      address: "153 Avenida Messina, Sarasota, FL 34242",
      cuisine_type: "Seafood & American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten"],
      allergens_handled: ["shellfish", "fish", "gluten", "dairy"],
      description: "Charming Siesta Key cottage restaurant with Gulf views. Gluten-free menu available. Staff trained on common allergens. Seafood-forward menu — discuss shellfish concerns.",
      website: "https://thecottagesiestakey.com",
      phone: "(941) 555-0429",
      image_url: "",
      verified: true,
    },
    {
      name: "Miguel's Restaurant",
      address: "6631 Midnight Pass Rd, Sarasota, FL 34242",
      cuisine_type: "French-Continental",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["shellfish"],
      allergens_handled: ["gluten", "dairy", "eggs", "shellfish"],
      description: "Elegant Siesta Key French-Continental dining since 1984. Staff well-versed in menu ingredients. Gluten-free and dairy-free modifications available. Call ahead for complex allergies.",
      website: "https://miguelsrestaurant.com",
      phone: "(941) 349-4024",
      image_url: "",
      verified: true,
    },
    {
      name: "C'est La Vie",
      address: "1553 Main St, Sarasota, FL 34236",
      cuisine_type: "French Bakery & Cafe",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "eggs", "nuts"],
      description: "Authentic French bakery and cafe on Main Street. Gluten-free pastries available but baked in a wheat-heavy environment. Salads and quiches are good options for mild sensitivities.",
      website: "https://cestlaviesarasota.com",
      phone: "(941) 906-9575",
      image_url: "",
      verified: true,
    },
    {
      name: "Screaming Goat Taqueria",
      address: "6606 Superior Ave, Sarasota, FL 34231",
      cuisine_type: "Tacos & Mexican",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy"],
      description: "Gulf Gate taqueria with creative taco combinations. Corn tortillas for all tacos — naturally gluten-free. Shared fryer for chips. Dairy used in crema and cheese.",
      website: "https://screaminggoattaqueria.com",
      phone: "(941) 555-0430",
      image_url: "",
      verified: true,
    },
  ];
}
