import type { RestaurantSeed } from "./restaurants";

// ── Portland restaurant data (13 restaurants) ────────────────────────────────

export function getPortlandRestaurants(): RestaurantSeed[] {
  return [
    // ═══ TIER 1: 100% Dedicated Facilities (2) ═══
    {
      name: "New Cascadia Traditional",
      address: "2502 SE Division St, Portland, OR 97202",
      cuisine_type: "Gluten-Free Bakery & Cafe",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["fish", "gluten", "shellfish"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy"],
      description: "Portland's premier 100% dedicated gluten-free bakery. Bagels, breads, pastries, pizza, and sandwiches — all in a celiac-safe facility with zero risk of cross-contamination. Wholesale supplier to local restaurants.",
      website: "https://newcascadiatraditional.com",
      phone: "(503) 477-7687",
      image_url: "",
      verified: true,
    },
    {
      name: "Ground Breaker Brewing",
      address: "2030 SE 7th Ave, Portland, OR 97214",
      cuisine_type: "Gluten-Free Brewery & Gastropub",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "soy", "nuts"],
      description: "The nation's first dedicated gluten-free brewery. Entire facility is 100% gluten-free — from the beer (brewed with chestnuts, lentils, and GF grains) to the full gastropub menu. Celiac-safe destination.",
      website: "https://groundbreakerbrewing.com",
      phone: "(503) 928-4195",
      image_url: "",
      verified: true,
    },

    // ═══ TIER 2: Certified Allergen Protocols (4) ═══
    {
      name: "Andina",
      address: "1314 NW Glisan St, Portland, OR 97209",
      cuisine_type: "Peruvian",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "peanuts", "eggs"],
      allergens_handled: ["gluten", "dairy", "soy", "nuts", "shellfish", "eggs"],
      description: "Pearl District's acclaimed Peruvian restaurant with a detailed gluten-free menu and dedicated fryer. Staff is exceptionally trained on allergens; kitchen follows rigorous protocols for all dietary restrictions.",
      website: "https://andinarestaurant.com",
      phone: "(503) 228-9535",
      image_url: "",
      verified: true,
    },
    {
      name: "Departure",
      address: "525 SW Morrison St, Portland, OR 97204",
      cuisine_type: "Modern Asian",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "peanuts", "eggs"],
      allergens_handled: ["gluten", "soy", "shellfish", "peanuts", "eggs"],
      description: "Rooftop Asian-fusion restaurant atop The Nines hotel with panoramic city views. Dedicated gluten-free menu and fryer. Detailed allergen guide; staff trained on navigating complex dietary needs.",
      website: "https://departureportland.com",
      phone: "(503) 802-5370",
      image_url: "",
      verified: true,
    },
    {
      name: "Blossoming Lotus",
      address: "1713 NE 15th Ave, Portland, OR 97212",
      cuisine_type: "Vegan & Gluten-Free",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy", "peanuts"],
      allergens_handled: ["gluten", "soy", "nuts"],
      description: "Irvington's beloved vegan restaurant with an entirely plant-based kitchen (no dairy or eggs). Dedicated gluten-free fryer and extensive GF menu. Staff trained on allergen cross-contact prevention.",
      website: "https://blossominglotuspdx.com",
      phone: "(503) 228-0048",
      image_url: "",
      verified: true,
    },
    {
      name: "Petunia's Pies & Pastries",
      address: "610 SW 12th Ave, Portland, OR 97205",
      cuisine_type: "Gluten-Free & Vegan Bakery",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "fish", "gluten", "peanuts", "sesame", "shellfish", "tree nuts", "soy"],
      allergens_handled: ["gluten", "soy", "nuts"],
      description: "Downtown's entirely gluten-free and vegan bakery. All items are free from gluten, dairy, and eggs. Dedicated facility for baking with separate prep for nut-free items. Cakes, pies, and pastries.",
      website: "https://petuniaspiesandpastries.com",
      phone: "(503) 841-5965",
      image_url: "",
      verified: true,
    },

    // ═══ TIER 3: Dietary-Friendly (7) ═══
    {
      name: "Pok Pok",
      address: "3226 SE Division St, Portland, OR 97202",
      cuisine_type: "Thai Street Food",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten", "peanuts", "sesame", "tree nuts", "soy"],
      allergens_handled: ["gluten", "soy", "shellfish", "peanuts", "fish"],
      description: "Andy Ricker's legendary Southeast Asian restaurant. Many dishes use fish sauce, soy, and peanuts extensively. Gluten-free options available but cross-contact risk in a busy kitchen. Staff well-informed.",
      website: "https://pokpokpdx.com",
      phone: "(503) 232-1387",
      image_url: "",
      verified: true,
    },
    {
      name: "Screen Door",
      address: "2337 E Burnside St, Portland, OR 97214",
      cuisine_type: "Southern Comfort",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["dairy", "eggs", "soy", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Kerns neighborhood's famous Southern kitchen known for fried chicken and weekend brunch lines. Gluten-free modifications available but kitchen is wheat-flour-heavy. Best for dairy or egg concerns.",
      website: "https://screendoorrestaurant.com",
      phone: "(503) 542-0880",
      image_url: "",
      verified: true,
    },
    {
      name: "Voodoo Doughnut",
      address: "22 SW 3rd Ave, Portland, OR 97204",
      cuisine_type: "Doughnuts",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy"],
      description: "Portland's iconic doughnut shop. Vegan doughnuts available (dairy-free and egg-free) and fried in shared oil. Gluten-free options not available — wheat flour throughout the facility.",
      website: "https://voodoodoughnut.com",
      phone: "(503) 241-4704",
      image_url: "",
      verified: true,
    },
    {
      name: "Tasty n Alder",
      address: "580 SW 12th Ave, Portland, OR 97205",
      cuisine_type: "New American Steakhouse",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["soy", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "nuts", "eggs"],
      description: "John Gorham's downtown steakhouse with global influences. Staff is knowledgeable about allergens; kitchen can modify most dishes. Gluten-free, dairy-free, and nut-free options available on request.",
      website: "https://tastynalder.com",
      phone: "(503) 621-9251",
      image_url: "",
      verified: true,
    },
    {
      name: "Nong's Khao Man Gai",
      address: "609 SE Ankeny St, Portland, OR 97214",
      cuisine_type: "Thai",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "soy"],
      allergens_handled: ["gluten", "soy"],
      description: "Simple, focused menu of chicken and rice that is naturally gluten-free. Soy-based sauce served on the side — request gluten-free soy sauce for full safety. Small kitchen, limited cross-contact risk.",
      website: "https://nongskhaomangaipdx.com",
      phone: "(503) 740-2907",
      image_url: "",
      verified: true,
    },
    {
      name: "Le Pigeon",
      address: "738 E Burnside St, Portland, OR 97214",
      cuisine_type: "French Fine Dining",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "shellfish"],
      allergens_handled: ["gluten", "dairy", "nuts", "eggs", "shellfish"],
      description: "Gabriel Rucker's James Beard award-winning French bistro. Intimate open kitchen with an exceptionally trained staff. Dietary restrictions can be accommodated with advance notice when booking.",
      website: "https://lepigeon.com",
      phone: "(503) 546-8796",
      image_url: "",
      verified: true,
    },
    {
      name: "Salt & Straw",
      address: "838 NW 23rd Ave, Portland, OR 97210",
      cuisine_type: "Ice Cream",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "shellfish"],
      allergens_handled: ["dairy", "eggs", "nuts", "gluten"],
      description: "Portland's beloved artisan ice cream shop. Vegan (coconut-based) flavors available for dairy-free and egg-free needs. Allergen guide for each flavor. Shared scooping equipment — ask about cross-contact.",
      website: "https://saltandstraw.com",
      phone: "(971) 271-8168",
      image_url: "",
      verified: true,
    },

    // ═══ AUTO-DISCOVERED (Tier 2-3 via Google Places) ═══
{
      name: "Screen Door Eastside",
      address: "2337 E Burnside St, Portland, OR 97214",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Observatory",
      address: "8115 SE Stark St, Portland, OR 97215",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Lechon",
      address: "113 SW Naito Pkwy, Portland, OR 97204",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Farmhouse Kitchen Thai Cuisine | Pearl District",
      address: "121 NW 9th Ave, Portland, OR 97209",
      cuisine_type: "Thai",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy","soy","peanuts"],
      description: "Auto-discovered via Google Places. A thai restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Q Restaurant & Bar",
      address: "828 SW 2nd Ave, Portland, OR 97204",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Portland City Grill",
      address: "111 SW 5th Ave 30th Floor, Portland, OR 97204",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Queen Mama's Kitchen",
      address: "406 SW Oak St, Portland, OR 97204",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Pine Street Market",
      address: "126 SW 2nd Ave, Portland, OR 97204",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Screen Door Pearl District",
      address: "1131 NW Couch St, Portland, OR 97209",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Departure Restaurant + Lounge",
      address: "525 SW Morrison St 15th Floor 15th Floor, Portland, OR 97204",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Canard",
      address: "734 E Burnside St, Portland, OR 97214",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Arden Restaurant Portland",
      address: "417 NW 10th Ave, Portland, OR 97209",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "OX Restaurant",
      address: "2225 NE Martin Luther King Jr Blvd, Portland, OR 97212",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Mucca Osteria",
      address: "1022 SW Morrison St, Portland, OR 97205",
      cuisine_type: "Italian",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy","eggs"],
      description: "Auto-discovered via Google Places. A italian restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Luc Lac Vietnamese Kitchen",
      address: "835 SW 2nd Ave, Portland, OR 97204",
      cuisine_type: "Vietnamese",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy","soy","peanuts"],
      description: "Auto-discovered via Google Places. A vietnamese restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Chart House",
      address: "5700 SW Terwilliger Blvd, Portland, OR 97239",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Jacqueline",
      address: "2500 SE Clinton St, Portland, OR 97202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Campana",
      address: "901 NE Oneonta St, Portland, OR 97211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "L’ Orange",
      address: "2005 SE 11th Ave, Portland, OR 97214",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Hearth & Vine",
      address: "10 NW 12th Ave, Portland, OR 97209",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "kann",
      address: "548 SE Ash St, Portland, OR 97214",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Fogo de Chão Brazilian Steakhouse",
      address: "930 SW 6th Ave, Portland, OR 97204",
      cuisine_type: "Steakhouse",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","eggs"],
      description: "Auto-discovered via Google Places. A steakhouse restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Urdaneta",
      address: "3033 NE Alberta St, Portland, OR 97211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Dolly Olive",
      address: "527 SW 12th Ave, Portland, OR 97205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Roe",
      address: "515 SW Broadway #100, Portland, OR 97205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Nostrana",
      address: "1401 SE Morrison St #101, Portland, OR 97214",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Tusk",
      address: "2448 E Burnside St, Portland, OR 97214",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Mother's Bistro & Bar",
      address: "121 SW 3rd Ave, Portland, OR 97204",
      cuisine_type: "French",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","eggs","tree nuts"],
      description: "Auto-discovered via Google Places. A french restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Lilia Comedor",
      address: "422 NW 8th Ave, Portland, OR 97209",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "El Gaucho Portland",
      address: "319 SW Broadway, Portland, OR 97205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Salty's on the Columbia River",
      address: "3839 NE Marine Dr, Portland, OR 97211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "NORMANDIE",
      address: "1005 SE Ankeny St, Portland, OR 97214",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Bellpine",
      address: "900 SW Washington St, Portland, OR 97205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Olympia Provisions",
      address: "107 SE Washington St, Portland, OR 97214",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Higgins",
      address: "1239 SW Broadway, Portland, OR 97205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Cabezon Restaurant",
      address: "5200 NE Sacramento St, Portland, OR 97213",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Cheryl's on 12th",
      address: "1135 SW Washington St, Portland, OR 97205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Besaws",
      address: "1545 NW 21st Ave, Portland, OR 97209",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Noble Rot",
      address: "1111 E Burnside St Fourth Floor, Portland, OR 97214",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Coquine",
      address: "6839 SE Belmont St, Portland, OR 97215",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Grassa",
      address: "1205 SW Washington St, Portland, OR 97205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Jake's Famous Crawfish",
      address: "401 SW 12th Ave, Portland, OR 97205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Street Disco",
      address: "4144A SE 60th Ave, Portland, OR 97206",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Shalom Y'all",
      address: "117 SE Taylor St #101, Portland, OR 97214",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Xiao Ye",
      address: "3832 NE Sandy Blvd, Portland, OR 97232",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Radio Room",
      address: "1101 NE Alberta St, Portland, OR 97211",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Slow Bar",
      address: "533 SE Grand Ave, Portland, OR 97214",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Gado Gado",
      address: "1801 NE Cesar E Chavez Blvd, Portland, OR 97212",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Tréla Greek Kitchen",
      address: "6000 NE Glisan St, Portland, OR 97213",
      cuisine_type: "Mediterranean",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","tree nuts"],
      description: "Auto-discovered via Google Places. A mediterranean restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Teardrop Lounge",
      address: "1015 NW Everett St, Portland, OR 97209",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Scotch Lodge",
      address: "215 SE 9th Ave #102, Portland, OR 97214",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Din Tai Fung",
      address: "700 SW 5th Ave, Portland, OR 97204",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Kells Irish Restaurant & Pub",
      address: "112 SW 2nd Ave, Portland, OR 97204",
      cuisine_type: "Gastropub",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A gastropub restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Wilf's Restaurant & Jazz Bar at Union Station",
      address: "800 NW 6th Ave, Portland, OR 97209",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "OK Omens",
      address: "1758 SE Hawthorne Blvd, Portland, OR 97214",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Midtown Beer Garden by Expensify",
      address: "431 SW Harvey Milk St, Portland, OR 97204",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Jake's Grill",
      address: "611 SW 10th Ave, Portland, OR 97205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Deschutes Brewery Portland Public House",
      address: "210 NW 11th Ave, Portland, OR 97209",
      cuisine_type: "Gastropub",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A gastropub restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Piattino",
      address: "1140 NW Everett St, Portland, OR 97209",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Southpark Seafood",
      address: "901 SW Salmon St, Portland, OR 97205",
      cuisine_type: "Seafood",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","shellfish"],
      description: "Auto-discovered via Google Places. A seafood restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Love Belizean",
      address: "1503 SW Broadway, Portland, OR 97201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Daily Feast",
      address: "837 SW 11th Ave, Portland, OR 97205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Gracie's",
      address: "729 SW 15th Ave, Portland, OR 97205",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Portland. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
  ];
}
