import type { RestaurantSeed } from "./restaurants";

// ── Atlanta restaurant data (60 restaurants) ──────────────────────────────────

export function getAtlantaRestaurants(): RestaurantSeed[] {
  return [
    // ═══ TIER 1: 100% Dedicated Facilities (4) ═══
    {
      name: "Arepa Mia",
      address: "10 N Clarendon Ave, Avondale Estates, GA 30002",
      cuisine_type: "Venezuelan (Gluten-Free)",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy", "soy", "peanuts", "tree nuts", "sesame"],
      allergens_handled: ["eggs", "shellfish", "fish"],
      description: "100% gluten-free Venezuelan arepas made from corn flour. Dedicated GF kitchen with no wheat on premises. House-made sauces are dairy-free and nut-free. Celiac-safe.",
      website: "https://arepamiaatl.com",
      phone: "404-600-3356",
      image_url: "",
      verified: true,
    },
    {
      name: "Hell Yeah Gluten Free",
      address: "900 DeKalb Ave NE, Atlanta, GA 30307",
      cuisine_type: "Gluten-Free Bakery & Cafe",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "peanuts", "tree nuts", "sesame", "soy"],
      allergens_handled: ["dairy", "eggs"],
      description: "Dedicated 100% gluten-free bakery in Inman Park. Biscuits, donuts, sandwiches, and pastries — all celiac-safe. Also free from peanuts and tree nuts. Vegan options available.",
      website: "https://hellyeahglutenfree.com",
      phone: "404-600-7757",
      image_url: "",
      verified: true,
    },
    {
      name: "Sally's Gluten Free Bakery",
      address: "5920 Roswell Rd, Sandy Springs, GA 30328",
      cuisine_type: "Gluten-Free Bakery",
      safety_tier: 1,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "soy", "sesame"],
      allergens_handled: ["dairy", "eggs", "tree nuts"],
      description: "Dedicated gluten-free bakery specializing in breads, cakes, and pastries. All products are celiac-safe. Dairy-free and egg-free options available. Also nut-free on request.",
      website: "https://sallysglutenfreebakery.com",
      phone: "404-497-9969",
      image_url: "",
      verified: true,
    },
    {
      name: "Soul Vegetarian",
      address: "879 Ralph David Abernathy Blvd SW, Atlanta, GA 30310",
      cuisine_type: "Vegan Soul Food",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "fish", "shellfish", "peanuts", "sesame"],
      allergens_handled: ["gluten", "soy", "tree nuts"],
      description: "100% vegan soul food restaurant with dedicated fryers. No animal products on premises. Gluten-free options clearly marked. Kalebone and BBQ tofu are must-tries.",
      website: "https://soulvegetarian.com",
      phone: "404-752-5194",
      image_url: "",
      verified: true,
    },

    // ═══ TIER 2: Certified Allergen Protocols (18) ═══
    {
      name: "True Food Kitchen",
      address: "3393 Peachtree Rd NE, Atlanta, GA 30326",
      cuisine_type: "Health-Conscious American",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy", "peanuts", "shellfish", "sesame"],
      allergens_handled: ["soy", "tree nuts", "eggs", "fish"],
      description: "Buckerhead location of the seasonal, health-driven chain. Detailed allergen matrix and well-trained staff. Most menu items can be modified for allergies.",
      website: "https://truefoodkitchen.com",
      phone: "404-228-5550",
      image_url: "",
      verified: true,
    },
    {
      name: "Flower Child",
      address: "3400 Around Lenox Rd NE, Atlanta, GA 30326",
      cuisine_type: "Health-Conscious Bowls",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy", "peanuts", "shellfish"],
      allergens_handled: ["soy", "tree nuts", "eggs", "sesame"],
      description: "Fast-casual spot in Lenox Square area with extensive GF, DF, and vegan options clearly labeled. Separate prep for allergen-sensitive dishes.",
      website: "https://iamaflowerchild.com",
      phone: "404-228-4552",
      image_url: "",
      verified: true,
    },
    {
      name: "Upbeet",
      address: "1071 Howell Mill Rd, Atlanta, GA 30318",
      cuisine_type: "Organic Bowls & Salads",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy", "peanuts", "tree nuts", "soy", "sesame"],
      allergens_handled: ["eggs", "shellfish"],
      description: "Westside organic bowls and salads with build-your-own options. All allergens clearly marked on digital menu. GF, DF, and vegan choices abundant.",
      website: "https://upbeet.com",
      phone: "404-254-4778",
      image_url: "",
      verified: true,
    },
    {
      name: "R. Thomas Deluxe Grill",
      address: "1812 Peachtree St NW, Atlanta, GA 30309",
      cuisine_type: "Health Food & Comfort",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy", "eggs", "peanuts", "shellfish", "sesame", "soy"],
      allergens_handled: ["tree nuts", "fish"],
      description: "Atlanta institution open 24/7 with extensive gluten-free, vegan, and paleo menus. Dedicated GF fryer and knowledgeable staff. Tropical bird-filled patio.",
      website: "https://rthomasdeluxegrill.com",
      phone: "404-872-2942",
      image_url: "",
      verified: true,
    },
    {
      name: "Cafe Sunflower",
      address: "2140 Peachtree Rd NW, Atlanta, GA 30309",
      cuisine_type: "Vegetarian & Vegan",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["peanuts", "shellfish", "fish", "sesame"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy", "tree nuts"],
      description: "Upscale vegetarian restaurant with dedicated gluten-free fryer. Extensive vegan menu. Staff trained on all major allergens. Soy-free options available.",
      website: "https://cafesunflower.com",
      phone: "404-352-8859",
      image_url: "",
      verified: true,
    },
    {
      name: "Herban Fix",
      address: "565 Peachtree St NE, Atlanta, GA 30308",
      cuisine_type: "Vegan Asian Fusion",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "fish", "shellfish"],
      allergens_handled: ["gluten", "soy", "peanuts", "tree nuts", "sesame"],
      description: "Plant-based pan-Asian restaurant in Midtown. Soy-free and gluten-free options clearly marked. Kitchen can isolate prep for most allergies. Elegant dining room.",
      website: "https://herbanfix.com",
      phone: "404-815-8787",
      image_url: "",
      verified: true,
    },
    {
      name: "Blue Sushi Sake Grill",
      address: "1080 Peachtree St NE, Atlanta, GA 30309",
      cuisine_type: "Japanese Sushi",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "peanuts", "sesame", "soy"],
      allergens_handled: ["gluten", "shellfish", "fish", "tree nuts"],
      description: "Sustainable sushi with dedicated gluten-free menu and fryer. Separate prep station for allergen-sensitive rolls. Extensive vegan sushi options. Midtown location.",
      website: "https://bluesushisakegrill.com",
      phone: "404-400-5227",
      image_url: "",
      verified: true,
    },
    {
      name: "Farm Burger",
      address: "3365 Piedmont Rd NE, Atlanta, GA 30305",
      cuisine_type: "Burgers",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "soy", "sesame"],
      allergens_handled: ["dairy", "eggs", "tree nuts"],
      description: "Grass-fed burger spot with dedicated gluten-free fryer and GF buns. Staff trained on allergen protocols. Gluten-free menu available. Buckhead location.",
      website: "https://farmburger.com",
      phone: "404-816-0602",
      image_url: "",
      verified: true,
    },
    {
      name: "Barcelona Wine Bar",
      address: "240 N Highland Ave NE, Atlanta, GA 30307",
      cuisine_type: "Spanish Tapas",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "peanuts", "soy"],
      allergens_handled: ["dairy", "eggs", "shellfish", "fish", "tree nuts"],
      description: "Spanish tapas with a dedicated gluten-free fryer. Detailed allergen guide available. Staff well-trained on allergies. Most tapas can be modified.",
      website: "https://barcelonawinebar.com",
      phone: "404-589-1010",
      image_url: "",
      verified: true,
    },
    {
      name: "The Porter Beer Bar",
      address: "1156 Euclid Ave NE, Atlanta, GA 30307",
      cuisine_type: "Gastropub",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "peanuts", "sesame", "soy"],
      allergens_handled: ["dairy", "eggs", "shellfish", "tree nuts"],
      description: "Little Five Points gastropub with extensive beer list and detailed allergen menu. Kitchen can accommodate most dietary needs. Gluten-free buns available.",
      website: "https://theporterbeerbar.com",
      phone: "404-223-0393",
      image_url: "",
      verified: true,
    },
    {
      name: "Leon's Full Service",
      address: "131 E Ponce de Leon Ave, Decatur, GA 30030",
      cuisine_type: "Gastropub",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "peanuts", "sesame"],
      allergens_handled: ["dairy", "eggs", "tree nuts", "shellfish"],
      description: "Decatur gastropub with dedicated fryer for gluten-free items. Seasonal menu with allergen notations. Excellent cocktail program. Outdoor bocce court.",
      website: "https://leonsfullservice.com",
      phone: "404-687-0500",
      image_url: "",
      verified: true,
    },
    {
      name: "Brick Store Pub",
      address: "125 E Court Square, Decatur, GA 30030",
      cuisine_type: "Gastropub",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["peanuts", "sesame", "soy"],
      allergens_handled: ["gluten", "dairy", "eggs", "shellfish", "tree nuts"],
      description: "Award-winning Decatur pub with Belgian beer focus. Kitchen can adapt most dishes for allergies. Gluten-free menu available. Staff takes allergies seriously.",
      website: "https://brickstorepub.com",
      phone: "404-687-0990",
      image_url: "",
      verified: true,
    },
    {
      name: "Wrecking Bar Brewpub",
      address: "292 Moreland Ave NE, Atlanta, GA 30307",
      cuisine_type: "Brewpub",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["peanuts", "sesame", "soy", "shellfish"],
      allergens_handled: ["gluten", "dairy", "eggs", "tree nuts", "fish"],
      description: "Little Five Points brewpub in a historic home. Seasonal farm-to-table menu with allergen-friendly options. GF buns available. House-brewed beers.",
      website: "https://wreckingbarbrewpub.com",
      phone: "404-221-2600",
      image_url: "",
      verified: true,
    },
    {
      name: "Murphy's",
      address: "997 Virginia Ave NE, Atlanta, GA 30306",
      cuisine_type: "American Bistro",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "peanuts", "sesame"],
      allergens_handled: ["dairy", "eggs", "shellfish", "fish", "tree nuts"],
      description: "Virginia-Highland institution since 1980. Extensive gluten-free menu with knowledgeable staff. Weekend brunch favorite. Can accommodate most allergies.",
      website: "https://murphysatlanta.com",
      phone: "404-872-0904",
      image_url: "",
      verified: true,
    },
    {
      name: "The General Muir",
      address: "1540 Avenue Pl, Atlanta, GA 30329",
      cuisine_type: "Jewish Deli",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["shellfish", "peanuts", "sesame", "soy"],
      allergens_handled: ["gluten", "dairy", "eggs", "tree nuts", "fish"],
      description: "Modern Jewish deli near Emory with dedicated gluten-free fryer. Pastrami and bagels are legendary. Allergen-trained staff. GF bagels available.",
      website: "https://thegeneralmuir.com",
      phone: "678-927-9131",
      image_url: "",
      verified: true,
    },
    {
      name: "Miller Union",
      address: "999 Brady Ave NW, Atlanta, GA 30318",
      cuisine_type: "Southern Farm-to-Table",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["peanuts", "sesame", "soy", "shellfish"],
      allergens_handled: ["gluten", "dairy", "eggs", "tree nuts", "fish"],
      description: "James Beard award-winning Southern restaurant. Seasonal menu with farm-fresh ingredients. Staff well-trained on allergens. Accommodate most dietary needs with notice.",
      website: "https://millerunion.com",
      phone: "678-733-8550",
      image_url: "",
      verified: true,
    },
    {
      name: "Staplehouse",
      address: "541 Edgewood Ave SE, Atlanta, GA 30312",
      cuisine_type: "American Tasting Menu",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["peanuts", "sesame", "soy", "shellfish", "fish"],
      allergens_handled: ["gluten", "dairy", "eggs", "tree nuts"],
      description: "Michelin-recognized tasting menu restaurant in Old Fourth Ward. Chef can accommodate most allergies with advance notice. Intimate dining experience.",
      website: "https://staplehouse.com",
      phone: "404-524-5005",
      image_url: "",
      verified: true,
    },
    {
      name: "Poor Calvin's",
      address: "510 Piedmont Ave NE, Atlanta, GA 30308",
      cuisine_type: "Asian Fusion",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "peanuts", "sesame", "soy", "shellfish", "fish"],
      allergens_handled: ["gluten", "eggs", "tree nuts"],
      description: "Asian-fusion with Southern influences. Dedicated gluten-free fryer and extensive GF menu. Staff knowledgeable about all allergens. Lobster fried rice is a signature.",
      website: "https://poorcalvins.com",
      phone: "404-254-4051",
      image_url: "",
      verified: true,
    },

    // ═══ TIER 3: Dietary-Friendly (38) ═══
    // ── Southern & Soul Food ──
    {
      name: "Mary Mac's Tea Room",
      address: "224 Ponce De Leon Ave NE, Atlanta, GA 30308",
      cuisine_type: "Southern",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "sesame"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Iconic Atlanta institution serving Southern comfort food since 1945. Known for fried chicken, collard greens, and friendly service. Gluten-free options available upon request.",
      website: "https://marymacs.com",
      phone: "404-876-1800",
      image_url: "",
      verified: true,
    },
    {
      name: "Busy Bee Cafe",
      address: "810 Martin Luther King Jr Dr SW, Atlanta, GA 30314",
      cuisine_type: "Southern Soul Food",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["dairy", "sesame"],
      allergens_handled: ["gluten", "soy", "eggs"],
      description: "Historic soul food landmark since 1947. Famous for fried chicken and oxtails. Many vegetable sides are naturally gluten-free. Community institution.",
      website: "https://thebusybeecafe.com",
      phone: "404-525-9212",
      image_url: "",
      verified: false,
    },
    {
      name: "Paschal's",
      address: "180 Northside Dr SW, Atlanta, GA 30313",
      cuisine_type: "Southern Soul Food",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "sesame"],
      allergens_handled: ["gluten", "dairy", "soy"],
      description: "Civil Rights-era landmark near the AUC. Famous fried chicken and peach cobbler. Many classic Southern sides are naturally gluten-free. Historic setting.",
      website: "https://paschalsatlanta.com",
      phone: "404-525-9393",
      image_url: "",
      verified: true,
    },
    {
      name: "Twisted Soul Cookhouse",
      address: "1133 Huff Rd NW, Atlanta, GA 30318",
      cuisine_type: "Southern Soul Food",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "sesame"],
      allergens_handled: ["gluten", "dairy", "soy", "tree nuts"],
      description: "Modern soul food with a global twist in West Midtown. Chef Deborah VanTrece creates innovative dishes. Staff can guide you on allergen-safe options.",
      website: "https://twistedsoulcookhouse.com",
      phone: "404-350-0028",
      image_url: "",
      verified: false,
    },
    {
      name: "South City Kitchen",
      address: "1144 Crescent Ave NE, Atlanta, GA 30309",
      cuisine_type: "Southern",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "sesame"],
      allergens_handled: ["gluten", "dairy", "shellfish", "tree nuts"],
      description: "Upscale Southern dining in Midtown. Shrimp and grits, fried green tomatoes — classics done right. Gluten-free menu available. Brunch favorite.",
      website: "https://southcitykitchen.com",
      phone: "404-873-7358",
      image_url: "",
      verified: true,
    },
    {
      name: "JCT Kitchen",
      address: "1198 Howell Mill Rd, Atlanta, GA 30318",
      cuisine_type: "Southern",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "sesame"],
      allergens_handled: ["gluten", "dairy", "eggs", "shellfish"],
      description: "Westside Southern restaurant with rooftop bar. Farm-to-table approach. Staff can accommodate allergies. Famous for fried chicken and deviled eggs.",
      website: "https://jctkitchen.com",
      phone: "404-355-2252",
      image_url: "",
      verified: true,
    },
    {
      name: "The Colonnade",
      address: "1879 Cheshire Bridge Rd NE, Atlanta, GA 30324",
      cuisine_type: "Southern",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "sesame"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Old-school Atlanta Southern restaurant since 1927. Classic fried chicken, yeast rolls, and strong cocktails. Gluten-free options available on request.",
      website: "https://thecolonnadeatlanta.com",
      phone: "404-874-5642",
      image_url: "",
      verified: false,
    },
    {
      name: "OK Cafe",
      address: "1284 W Paces Ferry Rd NW, Atlanta, GA 30327",
      cuisine_type: "Southern Diner",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["sesame"],
      allergens_handled: ["gluten", "dairy", "soy"],
      description: "Buckhead diner serving Southern comfort food all day. Meat-and-three plates with classic sides. Some gluten-free options available. Inform staff of allergies.",
      website: "https://okcafe.com",
      phone: "404-233-2888",
      image_url: "",
      verified: false,
    },

    // ── BBQ ──
    {
      name: "Fox Bros. Bar-B-Q",
      address: "1238 DeKalb Ave NE, Atlanta, GA 30307",
      cuisine_type: "BBQ",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "dairy"],
      allergens_handled: ["gluten", "soy"],
      description: "Texas-style BBQ in Atlanta. Most smoked meats are gluten-free. Sides vary — ask about flour-based thickeners. Always busy, plan accordingly.",
      website: "https://foxbrosbbq.com",
      phone: "404-577-4030",
      image_url: "",
      verified: true,
    },
    {
      name: "Community Q BBQ",
      address: "1361 Clairmont Rd, Decatur, GA 30033",
      cuisine_type: "BBQ",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "dairy"],
      allergens_handled: ["gluten", "soy"],
      description: "Family-run BBQ joint near Decatur. Meats smoked without gluten-containing ingredients. Mac and cheese is legendary but not GF. Ask about GF sides.",
      website: "https://communityqbbq.com",
      phone: "404-633-2080",
      image_url: "",
      verified: false,
    },
    {
      name: "Heirloom Market BBQ",
      address: "2243 Akers Mill Rd SE, Atlanta, GA 30339",
      cuisine_type: "Korean BBQ Fusion",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "dairy"],
      allergens_handled: ["gluten", "soy", "sesame"],
      description: "Korean-Southern BBQ fusion near the Chattahoochee. Most smoked meats are naturally GF. Korean spices may contain soy — check with staff for soy-free options.",
      website: "https://heirloommarketbbq.com",
      phone: "770-612-2502",
      image_url: "",
      verified: false,
    },
    {
      name: "Fat Matt's Rib Shack",
      address: "1811 Piedmont Ave NE, Atlanta, GA 30324",
      cuisine_type: "BBQ",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["dairy"],
      allergens_handled: ["gluten"],
      description: "No-frills BBQ shack with live blues. Ribs and chicken are the stars. Most meats are gluten-free; sauce may contain gluten. Casual, messy, delicious.",
      website: "https://fatmattsribshack.com",
      phone: "404-607-1622",
      image_url: "",
      verified: false,
    },

    // ── Steakhouse ──
    {
      name: "Bones",
      address: "3130 Piedmont Rd NE, Atlanta, GA 30305",
      cuisine_type: "Steakhouse",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "sesame"],
      allergens_handled: ["gluten", "dairy", "shellfish", "soy"],
      description: "Power-dining Buckhead steakhouse. Prime steaks and seafood. Staff is well-trained and will accommodate allergies. Gluten-free menu available on request.",
      website: "https://bonesrestaurant.com",
      phone: "404-237-2663",
      image_url: "",
      verified: true,
    },
    {
      name: "Chops Lobster Bar",
      address: "70 W Paces Ferry Rd NW, Atlanta, GA 30305",
      cuisine_type: "Steakhouse & Seafood",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "sesame"],
      allergens_handled: ["gluten", "dairy", "shellfish", "fish", "soy"],
      description: "Upscale Buckhead steakhouse and seafood spot. Exceptional service — staff will note all allergies. Most steaks are naturally GF. Extensive wine list.",
      website: "https://chopslobsterbar.com",
      phone: "404-262-2675",
      image_url: "",
      verified: true,
    },

    // ── Seafood ──
    {
      name: "The Optimist",
      address: "914 Howell Mill Rd, Atlanta, GA 30318",
      cuisine_type: "Seafood",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "sesame"],
      allergens_handled: ["shellfish", "fish", "dairy", "soy"],
      description: "Westside coastal seafood restaurant from Ford Fry. Oyster bar and wood-fired fish. Staff can navigate allergies. Many seafood dishes are naturally GF.",
      website: "https://theoptimistrestaurant.com",
      phone: "404-477-6260",
      image_url: "",
      verified: true,
    },
    {
      name: "Ray's on the River",
      address: "6700 Powers Ferry Rd NW, Sandy Springs, GA 30339",
      cuisine_type: "Seafood & Steak",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "sesame"],
      allergens_handled: ["shellfish", "fish", "dairy", "soy"],
      description: "Riverside dining on the Chattahoochee. Sunday brunch buffet is famous. Gluten-free menu available. Staff can help navigate seafood allergies.",
      website: "https://raysrestaurants.com",
      phone: "770-955-1187",
      image_url: "",
      verified: false,
    },

    // ── Italian ──
    {
      name: "Antico Pizza Napoletana",
      address: "1093 Hemphill Ave NW, Atlanta, GA 30318",
      cuisine_type: "Neapolitan Pizza",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["soy", "sesame"],
      allergens_handled: ["gluten", "dairy"],
      description: "Authentic Neapolitan pizza near Georgia Tech. Imported Italian ingredients. Flour-heavy kitchen — not suitable for celiac. Dairy-free pizza available on request.",
      website: "https://anticoatl.com",
      phone: "404-724-2333",
      image_url: "",
      verified: true,
    },
    {
      name: "BoccaLupo",
      address: "753 Edgewood Ave NE, Atlanta, GA 30307",
      cuisine_type: "Italian-American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "sesame"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy"],
      description: "Inman Park Italian-American spot with house-made pastas. Gluten-free pasta available. Small kitchen — cross-contamination possible. Best for mild sensitivities.",
      website: "https://boccalupoatl.com",
      phone: "404-577-2332",
      image_url: "",
      verified: false,
    },
    {
      name: "Sotto Sotto",
      address: "313 N Highland Ave NE, Atlanta, GA 30307",
      cuisine_type: "Italian",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["sesame"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy"],
      description: "Romantic Inman Park Italian restaurant. House-made pastas and risottos. Gluten-free pasta available. Staff knowledgeable about allergens.",
      website: "https://sottosottorestaurant.com",
      phone: "404-817-0015",
      image_url: "",
      verified: false,
    },
    {
      name: "La Grotta",
      address: "2637 Peachtree Rd NE, Atlanta, GA 30305",
      cuisine_type: "Italian Fine Dining",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["sesame"],
      allergens_handled: ["gluten", "dairy", "eggs", "fish"],
      description: "Buckhead's elegant underground Italian restaurant since 1978. Extensive wine list. Gluten-free pasta available. Staff can accommodate most allergies.",
      website: "https://lagrottaatlanta.com",
      phone: "404-231-1368",
      image_url: "",
      verified: false,
    },
    {
      name: "Pricci",
      address: "500 Pharr Rd NE, Atlanta, GA 30305",
      cuisine_type: "Modern Italian",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["sesame"],
      allergens_handled: ["gluten", "dairy", "soy", "tree nuts"],
      description: "Buckhead modern Italian with a lively bar. House-made pastas and wood-fired pizzas. Gluten-free pasta available. Staff will note allergies.",
      website: "https://pricciatlanta.com",
      phone: "404-237-2941",
      image_url: "",
      verified: false,
    },

    // ── Mexican & Tex-Mex ──
    {
      name: "Taqueria del Sol",
      address: "1200-B Howell Mill Rd, Atlanta, GA 30318",
      cuisine_type: "Mexican",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "sesame"],
      allergens_handled: ["gluten", "dairy", "soy"],
      description: "Beloved Atlanta taqueria with multiple locations. Most tacos on corn tortillas are naturally GF. Flour tortillas used for some items — specify corn. Creative weekly specials.",
      website: "https://taqueriadelsol.com",
      phone: "404-352-5811",
      image_url: "",
      verified: true,
    },
    {
      name: "Superica",
      address: "99 Krog St NE, Atlanta, GA 30307",
      cuisine_type: "Tex-Mex",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "sesame"],
      allergens_handled: ["gluten", "dairy", "soy"],
      description: "Ford Fry's Tex-Mex spot on the Beltline. Fajitas and enchiladas are stars. Corn tortillas available. Gluten-free menu on request. Bustling patio.",
      website: "https://superica.com",
      phone: "404-228-7111",
      image_url: "",
      verified: true,
    },
    {
      name: "Nuevo Laredo Cantina",
      address: "1495 Chattahoochee Ave NW, Atlanta, GA 30318",
      cuisine_type: "Mexican",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "soy"],
      description: "Westside hole-in-the-wall with incredible authentic Mexican food. Many naturally gluten-free dishes. Cash only. Busy at lunch — arrive early.",
      website: "",
      phone: "404-352-1464",
      image_url: "",
      verified: false,
    },

    // ── Buford Highway & International ──
    {
      name: "Pho Dai Loi",
      address: "4061 Jonesboro Rd, Forest Park, GA 30297",
      cuisine_type: "Vietnamese",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["dairy", "eggs"],
      allergens_handled: ["gluten", "soy", "shellfish", "fish"],
      description: "Authentic Vietnamese pho on Buford Highway. Rice noodles are naturally GF and DF. Pho broth is soy-free. Great for dairy and egg allergies.",
      website: "",
      phone: "404-366-2772",
      image_url: "",
      verified: false,
    },
    {
      name: "Nam Phuong",
      address: "4051 Buford Hwy NE, Atlanta, GA 30345",
      cuisine_type: "Vietnamese",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["dairy", "eggs"],
      allergens_handled: ["gluten", "soy", "shellfish", "fish", "peanuts"],
      description: "Buford Highway Vietnamese staple. Extensive menu with many GF rice noodle dishes. Spring rolls are naturally GF (rice paper). Peanuts used widely — inform staff of nut allergies.",
      website: "",
      phone: "404-929-6986",
      image_url: "",
      verified: false,
    },
    {
      name: "El Rey del Taco",
      address: "5288 Buford Hwy NE, Doraville, GA 30340",
      cuisine_type: "Mexican",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "soy"],
      description: "Late-night Buford Highway taqueria with authentic Mexican street tacos. Corn tortillas standard. Open late. Great for gluten-free diners. Cash preferred.",
      website: "",
      phone: "770-986-0086",
      image_url: "",
      verified: false,
    },

    // ── Asian ──
    {
      name: "Nan Thai Fine Dining",
      address: "1350 Spring St NW, Atlanta, GA 30309",
      cuisine_type: "Thai Fine Dining",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["dairy"],
      allergens_handled: ["gluten", "soy", "shellfish", "peanuts", "sesame"],
      description: "Award-winning Midtown Thai restaurant. Elegant setting with exceptional service. Staff trained on allergens. Gluten-free soy sauce available. Peanuts and shellfish used liberally.",
      website: "https://nanfinedining.com",
      phone: "404-870-9933",
      image_url: "",
      verified: true,
    },
    {
      name: "Tuk Tuk Thai",
      address: "1745 Peachtree St NE, Atlanta, GA 30309",
      cuisine_type: "Thai Street Food",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["dairy"],
      allergens_handled: ["gluten", "soy", "shellfish", "peanuts", "fish"],
      description: "Casual Thai street food near Piedmont Park. Many curries are naturally GF. Gluten-free soy sauce available. Busy lunch spot — best for mild sensitivities.",
      website: "https://tuktukatl.com",
      phone: "404-549-8857",
      image_url: "",
      verified: false,
    },
    {
      name: "Umi Sushi",
      address: "3050 Peachtree Rd NW, Atlanta, GA 30305",
      cuisine_type: "Japanese Sushi",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs"],
      allergens_handled: ["gluten", "soy", "shellfish", "fish", "sesame"],
      description: "Upscale Buckhead sushi destination. Omakase experience. Staff is exceptionally trained on allergies. Gluten-free tamari available. Notify when reserving.",
      website: "https://umiatlanta.com",
      phone: "404-841-0040",
      image_url: "",
      verified: true,
    },
    {
      name: "MF Sushi",
      address: "299 N Highland Ave NE, Atlanta, GA 30307",
      cuisine_type: "Japanese Sushi",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["dairy"],
      allergens_handled: ["gluten", "soy", "shellfish", "fish", "eggs", "sesame"],
      description: "Inman Park sushi destination from chef Chris Kinjo. Exceptional fish quality. Staff trained on allergens. Gluten-free tamari available. Premium experience.",
      website: "https://mfsushiatl.com",
      phone: "404-835-2122",
      image_url: "",
      verified: true,
    },
    {
      name: "O-Ku",
      address: "1085 Howell Mill Rd NW, Atlanta, GA 30318",
      cuisine_type: "Japanese Sushi",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["dairy"],
      allergens_handled: ["gluten", "soy", "shellfish", "fish", "eggs"],
      description: "Westside rooftop sushi with city views. Creative rolls and izakaya small plates. Gluten-free menu available. Staff can modify dishes for allergies.",
      website: "https://okusushiatl.com",
      phone: "404-500-2383",
      image_url: "",
      verified: false,
    },
    {
      name: "Eight Sushi Lounge",
      address: "930 Howell Mill Rd NW, Atlanta, GA 30318",
      cuisine_type: "Japanese Sushi",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["dairy"],
      allergens_handled: ["gluten", "soy", "shellfish", "fish", "eggs", "sesame"],
      description: "Westside sushi lounge with creative rolls. Extensive menu including cooked options. Gluten-free tamari available. Staff will guide you on allergen-safe choices.",
      website: "https://eightsushilounge.com",
      phone: "404-872-8882",
      image_url: "",
      verified: false,
    },

    // ── International & Eclectic ──
    {
      name: "Rumi's Kitchen",
      address: "6112 Roswell Rd, Sandy Springs, GA 30328",
      cuisine_type: "Persian",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "dairy", "sesame"],
      allergens_handled: ["soy", "tree nuts"],
      description: "Award-winning Persian restaurant with multiple Atlanta locations. Saffron-infused rice dishes are naturally GF. Kebabs are dairy-free. Nut-free on request.",
      website: "https://rumiskitchen.com",
      phone: "404-477-2100",
      image_url: "",
      verified: true,
    },
    {
      name: "Fogo de Chão",
      address: "3101 Piedmont Rd NE, Atlanta, GA 30305",
      cuisine_type: "Brazilian Steakhouse",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "sesame"],
      allergens_handled: ["dairy", "soy"],
      description: "Buckhead Brazilian steakhouse with continuous tableside meat service. Salad bar has extensive GF options. Most meats are naturally GF. Staff knowledgeable about allergens.",
      website: "https://fogo.com",
      phone: "404-995-7500",
      image_url: "",
      verified: true,
    },
    {
      name: "Empire State South",
      address: "999 Peachtree St NE, Atlanta, GA 30309",
      cuisine_type: "Southern",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["sesame"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy"],
      description: "Midtown Southern restaurant from chef Hugh Acheson. Seasonal farm-to-table. Staff trained on allergens. Gluten-free options available. Great for brunch.",
      website: "https://empirestatesouth.com",
      phone: "404-541-1105",
      image_url: "",
      verified: false,
    },

    // ── Fine Dining ──
    {
      name: "Bacchanalia",
      address: "1460 Ellsworth Industrial Blvd NW, Atlanta, GA 30318",
      cuisine_type: "American Fine Dining",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["peanuts", "sesame", "soy", "shellfish", "fish"],
      allergens_handled: ["gluten", "dairy", "eggs", "tree nuts"],
      description: "Atlanta's premier fine dining destination. Prix fixe tasting menu. Exceptional service — notify of allergies when booking. Kitchen will craft a safe menu.",
      website: "https://starprovisions.com",
      phone: "404-365-0410",
      image_url: "",
      verified: true,
    },
    {
      name: "Atlas",
      address: "88 W Paces Ferry Rd NW, Atlanta, GA 30305",
      cuisine_type: "American Fine Dining",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["peanuts", "sesame", "soy"],
      allergens_handled: ["gluten", "dairy", "eggs", "shellfish", "tree nuts"],
      description: "Buckhead fine dining inside the St. Regis. Art-filled dining room. Tasting menu with wine pairings. Staff will carefully accommodate allergies with advance notice.",
      website: "https://atlasrestaurant.com",
      phone: "404-600-6471",
      image_url: "",
      verified: true,
    },
    {
      name: "Aria",
      address: "490 E Paces Ferry Rd NE, Atlanta, GA 30305",
      cuisine_type: "American Fine Dining",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["peanuts", "sesame"],
      allergens_handled: ["gluten", "dairy", "eggs", "shellfish", "soy"],
      description: "Intimate Buckhead restaurant from chef Gerry Klaskala. Seasonal American menu. Staff will accommodate allergies with advance notice. Romantic ambiance.",
      website: "https://aria-atl.com",
      phone: "404-233-7673",
      image_url: "",
      verified: false,
    },
    {
      name: "Canoe",
      address: "4199 Paces Ferry Rd SE, Atlanta, GA 30339",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["sesame"],
      allergens_handled: ["gluten", "dairy", "eggs", "shellfish", "soy"],
      description: "Riverside restaurant on the Chattahoochee with stunning gardens. Upscale American cuisine. Staff trained on allergies. Gluten-free menu available. Perfect for special occasions.",
      website: "https://canoeatl.com",
      phone: "770-432-2663",
      image_url: "",
      verified: true,
    },
    {
      name: "Kimball House",
      address: "303 E Howard Ave, Decatur, GA 30030",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["peanuts", "sesame"],
      allergens_handled: ["gluten", "dairy", "eggs", "shellfish", "soy"],
      description: "Decatur's jewel — oyster bar and seasonal American menu. Historic train depot setting. Exceptional cocktail program. Staff trained on allergens.",
      website: "https://kimball-house.com",
      phone: "404-378-3502",
      image_url: "",
      verified: false,
    },
    {
      name: "Gunshow",
      address: "924 Garrett St SE, Atlanta, GA 30316",
      cuisine_type: "Eclectic",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["peanuts", "sesame"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy", "shellfish"],
      description: "Chef Kevin Gillespie's dim-sum style restaurant in Glenwood Park. Chefs present dishes tableside. Staff trained on allergens. Let them know your needs.",
      website: "https://gunshowatl.com",
      phone: "404-380-1886",
      image_url: "",
      verified: false,
    },

    // ── Breakfast & Brunch ──
    {
      name: "Home Grown",
      address: "968 Memorial Dr SE, Atlanta, GA 30316",
      cuisine_type: "Southern Breakfast",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["sesame"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Reynoldstown breakfast institution. Comfy chicken biscuit is famous. GF toast available. Kitchen is flour-heavy — best for mild sensitivities. Go early for brunch.",
      website: "",
      phone: "404-222-0455",
      image_url: "",
      verified: false,
    },
    {
      name: "Buttermilk Kitchen",
      address: "4225 Roswell Rd NE, Atlanta, GA 30342",
      cuisine_type: "Southern Breakfast",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["sesame"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy"],
      description: "Buckhead farm-to-table breakfast spot. Buttermilk pancakes and fried chicken biscuits are stars. GF options available. Busy brunch — expect a wait.",
      website: "https://buttermilkkitchen.com",
      phone: "404-254-4410",
      image_url: "",
      verified: false,
    },
    {
      name: "West Egg Cafe",
      address: "1100 Howell Mill Rd, Atlanta, GA 30318",
      cuisine_type: "Breakfast & Brunch",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["sesame"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy"],
      description: "Westside breakfast and brunch favorite. Extensive coffee program. GF toast and pancakes available. Gluten-free options marked on menu. Pimento cheese is a must.",
      website: "https://westeggcafe.com",
      phone: "404-872-3973",
      image_url: "",
      verified: false,
    },

    // ── Misc Notable ──
    {
      name: "The Varsity",
      address: "61 North Ave NW, Atlanta, GA 30308",
      cuisine_type: "American Fast Food",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["sesame"],
      allergens_handled: ["gluten", "dairy", "soy", "eggs"],
      description: "World's largest drive-in — Atlanta icon since 1928. Chili dogs and onion rings are classics. Not allergy-friendly but iconic. Gluten-free buns NOT available. Best for mild sensitivities.",
      website: "https://thevarsity.com",
      phone: "404-881-1706",
      image_url: "",
      verified: true,
    },
    {
      name: "Pappadeaux",
      address: "2830 Windy Hill Rd SE, Marietta, GA 30067",
      cuisine_type: "Cajun Seafood",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["sesame"],
      allergens_handled: ["gluten", "dairy", "shellfish", "fish", "soy"],
      description: "Large Cajun seafood restaurant chain. Extensive menu with fresh Gulf seafood. Gluten-free menu available. Can accommodate most allergies with notice.",
      website: "https://pappadeaux.com",
      phone: "770-984-8899",
      image_url: "",
      verified: false,
    },
    {
      name: "Nikolai's Roof",
      address: "255 Courtland St NE, Atlanta, GA 30303",
      cuisine_type: "French-Russian Fine Dining",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["peanuts", "sesame", "soy"],
      allergens_handled: ["gluten", "dairy", "eggs", "shellfish", "fish"],
      description: "Rooftop fine dining atop the Hilton downtown. French-Russian fusion with city views. Staff trained on allergens. Notify when reserving for best experience.",
      website: "https://nikolaisroof.com",
      phone: "404-221-6362",
      image_url: "",
      verified: false,
    },
  ];
}
