import type { RestaurantSeed } from "./restaurants";

// ── Chicago restaurant data (18 restaurants) ────────────────────────────────

export function getChicagoRestaurants(): RestaurantSeed[] {
  return [
    // ═══ TIER 1: 100% Dedicated Facilities (3) ═══
    {
      name: "Wheat's End Cafe & Bakery",
      address: "543 W Diversey Pkwy, Chicago, IL 60614",
      cuisine_type: "Gluten-Free Bakery & Cafe",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy"],
      description: "Chicago's beloved 100% dedicated gluten-free cafe and bakery. Everything from popovers to pancakes, English muffins to fried chicken is completely celiac-safe with zero cross-contamination risk.",
      website: "https://wheatsendcafe.com",
      phone: "(773) 661-6182",
      image_url: "",
      verified: true,
    },
    {
      name: "Bloom Plant Based Kitchen",
      address: "1559 N Milwaukee Ave, Chicago, IL 60622",
      cuisine_type: "Vegan & Gluten-Free",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten", "peanuts", "sesame", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy", "nuts"],
      description: "100% plant-based kitchen in Wicker Park with an entirely gluten-free facility. Creative globally-inspired bowls, tacos, and small plates. No dairy, eggs, or gluten on premises.",
      website: "https://bloompb.com",
      phone: "(773) 687-8862",
      image_url: "",
      verified: true,
    },
    {
      name: "Defloured: A Gluten Free Bakery",
      address: "1477 W Balmoral Ave, Chicago, IL 60640",
      cuisine_type: "Gluten-Free Bakery",
      safety_tier: 1,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten", "peanuts", "sesame", "soy", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "eggs", "nuts"],
      description: "Andersonville's dedicated gluten-free bakery crafting cookies, brownies, bars, and celebration cakes. 100% gluten-free facility — celiac-safe treats for every occasion.",
      website: "https://defloured.com",
      phone: "(773) 754-7140",
      image_url: "",
      verified: true,
    },

    // ═══ TIER 2: Certified Allergen Protocols (5) ═══
    {
      name: "Ema",
      address: "74 W Illinois St, Chicago, IL 60654",
      cuisine_type: "Mediterranean",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "peanuts", "eggs"],
      allergens_handled: ["gluten", "dairy", "nuts", "shellfish"],
      description: "River North Mediterranean hotspot with an extensive gluten-free menu and dedicated fryer. Staff is exceptionally well-trained on allergens; the kitchen uses color-coded cutting boards and separate prep zones.",
      website: "https://emachicago.com",
      phone: "(312) 527-5586",
      image_url: "",
      verified: true,
    },
    {
      name: "True Food Kitchen",
      address: "1 W Erie St, Chicago, IL 60654",
      cuisine_type: "Health-Conscious American",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "soy", "peanuts", "eggs"],
      allergens_handled: ["gluten", "dairy", "soy", "peanuts", "tree nuts", "shellfish"],
      description: "Seasonal, health-driven restaurant with detailed allergen matrix at the River North location. Staff trained on all major allergens; kitchen can isolate prep for most dietary needs.",
      website: "https://truefoodkitchen.com",
      phone: "(312) 204-6981",
      image_url: "",
      verified: true,
    },
    {
      name: "Beatrix",
      address: "519 N Clark St, Chicago, IL 60654",
      cuisine_type: "American Cafe & Bakery",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy", "peanuts"],
      allergens_handled: ["gluten", "dairy", "nuts", "eggs"],
      description: "Lettuce Entertain You's health-focused concept with clearly labeled gluten-free, vegetarian, and vegan options. Allergen guide available and staff is trained on cross-contact protocols.",
      website: "https://beatrixrestaurants.com",
      phone: "(312) 284-1377",
      image_url: "",
      verified: true,
    },
    {
      name: "Cafe Ba-Ba-Reeba!",
      address: "2024 N Halsted St, Chicago, IL 60614",
      cuisine_type: "Spanish Tapas",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "shellfish", "nuts", "eggs"],
      description: "Lincoln Park's iconic Spanish tapas restaurant with a detailed gluten-free menu and dedicated fryer for GF items. Staff trained on major allergens; kitchen follows strict allergen protocols for modified dishes.",
      website: "https://cafebabareeba.com",
      phone: "(773) 935-5000",
      image_url: "",
      verified: true,
    },
    {
      name: "The Purple Pig",
      address: "444 Michigan Ave, Chicago, IL 60611",
      cuisine_type: "Mediterranean Small Plates",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "nuts", "shellfish"],
      description: "Magnificent Mile institution serving cheese, swine, and wine with strong allergen awareness. Kitchen can modify most dishes; staff is knowledgeable about ingredient sourcing and can guide safe choices.",
      website: "https://thepurplepigchicago.com",
      phone: "(312) 464-1744",
      image_url: "",
      verified: true,
    },

    // ═══ TIER 3: Dietary-Friendly (10) ═══
    {
      name: "Lou Malnati's Pizzeria",
      address: "439 N Wells St, Chicago, IL 60654",
      cuisine_type: "Deep-Dish Pizza",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "tree nuts"],
      allergens_handled: ["gluten", "dairy"],
      description: "Chicago's iconic deep-dish pizza institution. Gluten-free crust available at all locations but prepared in a shared kitchen with wheat flour throughout. Not suitable for celiac diners.",
      website: "https://loumalnatis.com",
      phone: "(312) 828-9800",
      image_url: "",
      verified: true,
    },
    {
      name: "Girl & the Goat",
      address: "809 W Randolph St, Chicago, IL 60607",
      cuisine_type: "Global Small Plates",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "soy"],
      allergens_handled: ["gluten", "dairy", "nuts", "shellfish", "eggs"],
      description: "Stephanie Izard's West Loop flagship. Staff is well-trained on allergens and the kitchen can accommodate most dietary needs with advance notice. Menu changes seasonally — discuss restrictions when booking.",
      website: "https://girlandthegoat.com",
      phone: "(312) 492-6262",
      image_url: "",
      verified: true,
    },
    {
      name: "Au Cheval",
      address: "800 W Randolph St, Chicago, IL 60607",
      cuisine_type: "American Diner & Burgers",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["fish", "shellfish", "soy"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Famous for one of the country's best burgers in a bustling diner setting. Gluten-free bun available but kitchen handles high volume. Shared fryers — not ideal for severe allergies.",
      website: "https://auchevaldiner.com",
      phone: "(312) 929-4580",
      image_url: "",
      verified: true,
    },
    {
      name: "Portillo's",
      address: "100 W Ontario St, Chicago, IL 60654",
      cuisine_type: "Chicago-Style Fast Casual",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "soy"],
      allergens_handled: ["gluten", "dairy", "soy"],
      description: "Legendary Chicago hot dogs and Italian beef. Gluten-free buns available for hot dogs. Italian beef can be ordered without bread. High-volume kitchen — best for mild sensitivities.",
      website: "https://portillos.com",
      phone: "(312) 587-8910",
      image_url: "",
      verified: true,
    },
    {
      name: "The Publican",
      address: "837 W Fulton Market, Chicago, IL 60607",
      cuisine_type: "Farm-to-Table American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["shellfish", "fish"],
      allergens_handled: ["gluten", "dairy", "shellfish", "eggs"],
      description: "Fulton Market's beer-focused farmhouse restaurant. Staff is knowledgeable about ingredients; menu clearly marked for common allergens. Many vegetable dishes naturally gluten-free. Discuss needs when booking.",
      website: "https://thepublicanrestaurant.com",
      phone: "(312) 733-9555",
      image_url: "",
      verified: true,
    },
    {
      name: "Pequod's Pizza",
      address: "2207 N Clybourn Ave, Chicago, IL 60614",
      cuisine_type: "Deep-Dish Pizza",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "shellfish"],
      allergens_handled: ["gluten", "dairy"],
      description: "Cult-favorite deep dish known for its caramelized cheese crust. No gluten-free crust available — celiac diners should look elsewhere. Dairy-free modifications extremely limited.",
      website: "https://pequodspizza.com",
      phone: "(773) 327-1512",
      image_url: "",
      verified: true,
    },
    {
      name: "avec",
      address: "615 W Randolph St, Chicago, IL 60661",
      cuisine_type: "Mediterranean Small Plates",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "shellfish"],
      allergens_handled: ["gluten", "dairy", "nuts", "shellfish"],
      description: "West Loop Mediterranean favorite with communal dining. Menu marks gluten-free and vegetarian dishes. Staff can guide allergy-safe choices from the seasonal menu. Inform server of restrictions.",
      website: "https://avecrestaurant.com",
      phone: "(312) 377-2002",
      image_url: "",
      verified: true,
    },
    {
      name: "Little Goat Diner",
      address: "3325 N Southport Ave, Chicago, IL 60657",
      cuisine_type: "Diner & Brunch",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["fish", "shellfish", "sesame"],
      allergens_handled: ["gluten", "dairy", "eggs", "nuts"],
      description: "Stephanie Izard's Lakeview diner with creative brunch fare. Gluten-free bread available and staff is allergy-aware. Open kitchen — celiac diners should discuss cross-contact with server.",
      website: "https://littlegoatchicago.com",
      phone: "(773) 661-6144",
      image_url: "",
      verified: true,
    },
    {
      name: "Duck Duck Goat",
      address: "857 W Fulton Market, Chicago, IL 60607",
      cuisine_type: "Chinese-American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "fish"],
      allergens_handled: ["gluten", "soy", "shellfish", "peanuts", "eggs"],
      description: "Stephanie Izard's Chinese-inspired Fulton Market spot. Kitchen can modify many dishes for gluten-free diners (tamari available). Widespread soy and peanut use — discuss allergies with server.",
      website: "https://duckduckgoatchicago.com",
      phone: "(312) 902-3825",
      image_url: "",
      verified: true,
    },
    {
      name: "Pizzeria Portofino",
      address: "317 N Clark St, Chicago, IL 60654",
      cuisine_type: "Italian & Pizza",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "fish"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Riverwalk Italian restaurant with waterfront dining. Gluten-free pasta and pizza crust available. Shared kitchen — cross-contamination risk for celiac diners. Staff informed on allergen modifications.",
      website: "https://pizzeriaportofino.com",
      phone: "(312) 900-9018",
      image_url: "",
      verified: true,
    },

    // ═══ AUTO-DISCOVERED (Tier 2-3 via Google Places) ═══
{
      name: "Aba",
      address: "302 N Green St 3rd Floor, Chicago, IL 60607",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "River Roast",
      address: "315 N LaSalle St, Chicago, IL 60654",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Alla Vita",
      address: "564 W Randolph St, Chicago, IL 60661",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Dearborn",
      address: "145 N Dearborn St, Chicago, IL 60602",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "AMBAR Restaurant, Chicago",
      address: "700 N Clark St, Chicago, IL 60654",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Somerset",
      address: "1112 N State St, Chicago, IL 60610",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Purple Pig Restaurant",
      address: "444 N Michigan Ave Upper Level, Chicago, IL 60611",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Monteverde Restaurant & Pastificio",
      address: "1020 W Madison St, Chicago, IL 60607",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Maple & Ash",
      address: "8 W Maple St, Chicago, IL 60610",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Alinea",
      address: "1723 N Halsted St, Chicago, IL 60614",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Bavette's Bar & Boeuf",
      address: "218 W Kinzie St, Chicago, IL 60654",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Beatnik On The River",
      address: "180 N Wacker Dr, Chicago, IL 60606",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Carnivale Chicago",
      address: "702 W Fulton St, Chicago, IL 60661",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Boka",
      address: "1729 N Halsted St, Chicago, IL 60614",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Siena Tavern",
      address: "51 W Kinzie St, Chicago, IL 60654",
      cuisine_type: "Gastropub",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A gastropub restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "STK Steakhouse",
      address: "9 W Kinzie St, Chicago, IL 60654",
      cuisine_type: "Steakhouse",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","eggs"],
      description: "Auto-discovered via Google Places. A steakhouse restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Giordano's",
      address: "130 E Randolph St, Chicago, IL 60601",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Remington's",
      address: "20 N Michigan Ave, Chicago, IL 60602",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "La Grande Boucherie Chicago",
      address: "431 N Dearborn St, Chicago, IL 60654",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Kitchen + Kocktails By Kevin Kelley - Chicago",
      address: "339 N Dearborn St, Chicago, IL 60654",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Il Porcellino",
      address: "59 W Hubbard St #2, Chicago, IL 60654",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Rose Mary",
      address: "932 W Fulton St, Chicago, IL 60607",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Lou Mitchell's",
      address: "565 W Jackson Blvd, Chicago, IL 60661",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Elephant & Castle",
      address: "185 N Wabash Ave, Chicago, IL 60601",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Ocean Prime",
      address: "87 E Wacker Dr, Chicago, IL 60601",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Crying Tiger",
      address: "51 W Hubbard St, Chicago, IL 60654",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Gibsons Italia",
      address: "233 N Canal St, Chicago, IL 60606",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Doc B's Restaurant (Gold Coast)",
      address: "100 E Walton St, Chicago, IL 60611",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Yardbird",
      address: "530 N Wabash Ave, Chicago, IL 60654",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Porter Kitchen & Deck",
      address: "150 N Riverside Plaza, Chicago, IL 60606",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Greek Islands",
      address: "200 S Halsted St, Chicago, IL 60661",
      cuisine_type: "Mediterranean",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","tree nuts"],
      description: "Auto-discovered via Google Places. A mediterranean restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Gage",
      address: "24 S Michigan Ave, Chicago, IL 60603",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Momotaro",
      address: "820 W Lake St, Chicago, IL 60607",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Smyth",
      address: "177 N Ada St #101, Chicago, IL 60607",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "avec Restaurant",
      address: "615 W Randolph St, Chicago, IL 60661",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Wildberry Pancakes & Cafe",
      address: "130 E Randolph St, Chicago, IL 60601",
      cuisine_type: "Cafe",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A cafe restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Cindy's Rooftop",
      address: "12 S Michigan Ave, Chicago, IL 60603",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "RL Restaurant",
      address: "115 E Chicago Ave, Chicago, IL 60611",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Berghoff Restaurant",
      address: "17 W Adams St, Chicago, IL 60603",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Eleven City Diner",
      address: "1112 S Wabash Ave, Chicago, IL 60605",
      cuisine_type: "American Diner",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american diner restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Storyville Chicago",
      address: "712 N Clark St, Chicago, IL 60654",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Roanoke Restaurant",
      address: "135 W Madison St, Chicago, IL 60603",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Joe's Seafood, Prime Steak & Stone Crab",
      address: "60 E Grand Ave, Chicago, IL 60611",
      cuisine_type: "Steakhouse",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","shellfish","eggs"],
      description: "Auto-discovered via Google Places. A steakhouse restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "State and Lake Chicago Tavern",
      address: "201 N State St Fl 1, Chicago, IL 60601",
      cuisine_type: "Gastropub",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A gastropub restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Mercadito",
      address: "108 W Kinzie St, Chicago, IL 60654",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Smith",
      address: "400 N Clark St, Chicago, IL 60654",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Harry Caray's Italian Steakhouse",
      address: "33 W Kinzie St, Chicago, IL 60654",
      cuisine_type: "Italian",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","eggs"],
      description: "Auto-discovered via Google Places. A italian restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Tavern On Rush",
      address: "1015 N Rush St, Chicago, IL 60611",
      cuisine_type: "Gastropub",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A gastropub restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Cira",
      address: "200 N Green St, Chicago, IL 60607",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Goddess and the Baker, 33 S Wabash-Millennium Park",
      address: "33 S Wabash Ave, Chicago, IL 60603",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Lil' Ba-Ba-Reeba!",
      address: "441 N Clark St #1, Chicago, IL 60654",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Exchange",
      address: "224 S Michigan Ave, Chicago, IL 60604",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Bar Mar",
      address: "120 N Wacker Dr, Chicago, IL 60606",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Chicago. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
  ];
}
