import type { RestaurantSeed } from "./restaurants";

// ── St. Louis restaurant data (55 restaurants) ────────────────────────────────

export function getStLouisRestaurants(): RestaurantSeed[] {
  return [
    // ═══ TIER 1: 100% Dedicated Facilities (7) ═══
    {
      name: "New Day Gluten Free",
      address: "7807 Clayton Rd, Clayton, MO 63117",
      cuisine_type: "Gluten-Free Bakery & Cafe",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy"],
      description: "St. Louis's premier 100% dedicated gluten-free bakery and cafe. Everything from fried chicken sandwiches to donuts is completely celiac-safe with zero cross-contamination risk.",
      website: "https://newdayglutenfree.com",
      phone: "(314) 644-1000",
      image_url: "",
      verified: true,
    },
    {
      name: "Lona's Lil Eats",
      address: "2199 California Ave, St. Louis, MO 63104",
      cuisine_type: "Asian Fusion (Allergy-Conscious)",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "soy", "peanuts"],
      description: "Beloved Fox Park eatery with an entirely gluten-free kitchen. Giant rice paper wraps, stir-fries, and salads — all prepared in a dedicated gluten-free facility.",
      website: "https://lonaslileats.com",
      phone: "(314) 772-8200",
      image_url: "",
      verified: true,
    },
    {
      name: "Revel Kitchen",
      address: "8388 Musick Memorial Dr, Brentwood, MO 63144",
      cuisine_type: "Gluten-Free & Paleo",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "gluten", "sesame", "soy"],
      allergens_handled: ["gluten", "dairy", "soy", "eggs", "nuts"],
      description: "Health-focused eatery with a kitchen free from gluten, dairy, soy, and refined sugar. Build-your-own bowls with grass-fed proteins and fresh veggies. Paleo and Whole30 compliant options.",
      website: "https://revelkitchen.com",
      phone: "(314) 394-2211",
      image_url: "",
      verified: true,
    },
    {
      name: "SweetArt Bakeshop",
      address: "2203 S 39th St, St. Louis, MO 63110",
      cuisine_type: "Vegan Bakery & Cafe",
      safety_tier: 1,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "soy"],
      allergens_handled: ["gluten", "soy", "nuts"],
      description: "Beloved Shaw neighborhood bakery that is 100% plant-based — no dairy or eggs in the facility. Cakes, cupcakes, cookies, and savory lunch items. Gluten-free options clearly labeled.",
      website: "https://sweetartstl.com",
      phone: "(314) 771-4278",
      image_url: "",
      verified: true,
    },
    {
      name: "Confluence Kombucha",
      address: "4507 Manchester Ave, St. Louis, MO 63110",
      cuisine_type: "Gluten-Free Cafe & Kombucha Bar",
      safety_tier: 1,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten"],
      allergens_handled: ["gluten", "dairy", "soy"],
      description: "Dedicated gluten-free cafe and kombucha taproom in The Grove. Light bites, toasts, and salads all prepared in a gluten-free facility. Dairy-free options available.",
      website: "https://confluencekombucha.com",
      phone: "(314) 555-0300",
      image_url: "",
      verified: true,
    },
    {
      name: "The Vine Vegan Cafe",
      address: "7441 S Grand Blvd, St. Louis, MO 63111",
      cuisine_type: "Vegan American",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten"],
      allergens_handled: ["gluten", "soy", "nuts"],
      description: "100% vegan cafe in South City with dedicated gluten-free fryer and prep area. Burgers, wraps, and bowls — all plant-based with clear allergen labeling for the top 8.",
      website: "https://thevinestl.com",
      phone: "(314) 555-0301",
      image_url: "",
      verified: true,
    },
    {
      name: "Prioritized Pastries",
      address: "315 N Kirkwood Rd, Kirkwood, MO 63122",
      cuisine_type: "Gluten-Free & Vegan Bakery",
      safety_tier: 1,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten", "sesame", "soy"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy", "nuts"],
      description: "Dedicated gluten-free, dairy-free, egg-free, and soy-free bakery. Custom cakes, cookies, and breads — free from the top 4 common allergens. Celiac-safe and allergy-conscious.",
      website: "https://prioritizedpastries.com",
      phone: "(314) 555-0302",
      image_url: "",
      verified: true,
    },

    // ═══ TIER 2: Certified Allergen Protocols (13) ═══
    {
      name: "Tree House",
      address: "3177 S Grand Blvd, St. Louis, MO 63118",
      cuisine_type: "Vegetarian & Vegan",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten", "soy", "peanuts"],
      allergens_handled: ["gluten", "dairy", "soy", "nuts", "eggs"],
      description: "South Grand vegetarian staple with extensive vegan and gluten-free menu sections. Dedicated fryer for gluten-free items and well-trained staff on cross-contact protocols.",
      website: "https://treehousevegetarian.com",
      phone: "(314) 932-5588",
      image_url: "",
      verified: true,
    },
    {
      name: "Seedz Cafe",
      address: "6344 S Rosebury Ave, St. Louis, MO 63105",
      cuisine_type: "Organic Plant-Based",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "peanuts"],
      allergens_handled: ["gluten", "dairy", "soy", "nuts"],
      description: "DeMun neighborhood organic, plant-based cafe. Gluten-free, soy-free, and nut-free options clearly marked. Separate prep stations and dedicated fryer for allergen-free items.",
      website: "https://seedzcafe.com",
      phone: "(314) 725-2066",
      image_url: "",
      verified: true,
    },
    {
      name: "Frida's",
      address: "622 N New Ballas Rd, Creve Coeur, MO 63141",
      cuisine_type: "Plant-Based American",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["eggs", "peanuts"],
      allergens_handled: ["gluten", "soy", "nuts", "dairy"],
      description: "Upscale plant-based restaurant with full allergen matrix. Dedicated gluten-free fryer, isolated prep areas, and staff trained on all major allergens. Extensive gluten-free and soy-free menu.",
      website: "https://fridasstl.com",
      phone: "(314) 569-1900",
      image_url: "",
      verified: true,
    },
    {
      name: "The Corner Pub and Grill",
      address: "15824 Fountain Plaza Dr, Ellisville, MO 63011",
      cuisine_type: "American Pub (Allergy-Friendly)",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["eggs", "peanuts", "tree nuts", "sesame"],
      allergens_handled: ["gluten", "dairy", "soy", "eggs"],
      description: "Family-friendly pub with one of the largest gluten-free menus in the Midwest. Dedicated fryer and prep area for gluten-free items. Staff undergoes regular allergy training.",
      website: "https://cornerpubandgrill.com",
      phone: "(636) 220-2200",
      image_url: "",
      verified: true,
    },
    {
      name: "Britt's Bakehouse",
      address: "607 E Lockwood Ave, Webster Groves, MO 63119",
      cuisine_type: "Gluten-Free Bakery",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten", "soy", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "eggs", "nuts"],
      description: "Bakery specializing in gluten-free goods with rigorous cross-contamination protocols. While the facility also handles wheat for select items, all gluten-free products are made on isolated equipment.",
      website: "https://brittsbakehouse.com",
      phone: "(314) 555-0303",
      image_url: "",
      verified: true,
    },
    {
      name: "GO! Cali Style Tacos",
      address: "13352 Manchester Rd, Des Peres, MO 63131",
      cuisine_type: "California-Style Mexican",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "soy"],
      description: "California-style taqueria with dedicated gluten-free fryer for chips and tacos. Corn tortillas are standard; separate prep area for allergen-sensitive orders. Staff trained on celiac needs.",
      website: "https://gocalistyle.com",
      phone: "(314) 555-0304",
      image_url: "",
      verified: true,
    },
    {
      name: "Meskerem Ethiopian Restaurant",
      address: "3210 S Grand Blvd, St. Louis, MO 63118",
      cuisine_type: "Ethiopian",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy", "tree nuts"],
      allergens_handled: ["gluten", "dairy"],
      description: "Authentic Ethiopian on South Grand with naturally gluten-free injera (100% teff) available. Staff knowledgeable about allergens; most dishes are dairy-free and can be made gluten-free.",
      website: "https://meskeremstl.com",
      phone: "(314) 772-4442",
      image_url: "",
      verified: true,
    },
    {
      name: "The Mud House",
      address: "2101 Cherokee St, St. Louis, MO 63118",
      cuisine_type: "Coffee Shop & Cafe",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "sesame"],
      allergens_handled: ["gluten", "dairy", "eggs", "soy"],
      description: "Cherokee Street coffee house with extensive gluten-free and vegan baked goods from local bakeries. Allergen labels on all items; separate tongs and prep surfaces.",
      website: "https://themudhousestl.com",
      phone: "(314) 776-6599",
      image_url: "",
      verified: true,
    },
    {
      name: "Vicia",
      address: "4260 Forest Park Ave, St. Louis, MO 63108",
      cuisine_type: "Farm-to-Table New American",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["nuts", "sesame"],
      allergens_handled: ["gluten", "dairy", "nuts", "eggs", "shellfish"],
      description: "Award-winning vegetable-forward fine dining. Staff thoroughly trained on all menu ingredients and can accommodate most dietary restrictions with advance notice. Seasonal menu with detailed allergen guide.",
      website: "https://viciarestaurant.com",
      phone: "(314) 553-9239",
      image_url: "",
      verified: true,
    },
    {
      name: "Bulrush",
      address: "3307 Washington Ave, St. Louis, MO 63103",
      cuisine_type: "Ozark-Inspired Fine Dining",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy"],
      allergens_handled: ["gluten", "dairy", "nuts", "eggs"],
      description: "James Beard-nominated tasting menu restaurant exploring Ozark foodways. Chef Rob Connoley is deeply allergy-aware; most dietary restrictions can be accommodated with advance notice.",
      website: "https://bulrushstl.com",
      phone: "(314) 449-1208",
      image_url: "",
      verified: true,
    },
    {
      name: "The Fountain on Locust",
      address: "3037 Locust St, St. Louis, MO 63103",
      cuisine_type: "American Retro & Ice Cream",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["soy"],
      allergens_handled: ["gluten", "dairy", "eggs", "nuts"],
      description: "Art deco ice cream parlor and restaurant with detailed allergen menu. Gluten-free soups, salads, and ice cream options. Dairy-free and vegan ice cream available. Staff trained on cross-contact.",
      website: "https://fountainonlocust.com",
      phone: "(314) 535-7800",
      image_url: "",
      verified: true,
    },
    {
      name: "PW Pizza",
      address: "2017 Chouteau Ave, St. Louis, MO 63103",
      cuisine_type: "Pizza",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy"],
      allergens_handled: ["gluten", "dairy"],
      description: "Lafayette Square pizzeria with gluten-free crust prepared in an isolated prep area with separate utensils. Dairy-free cheese available. Staff trained on allergen protocols.",
      website: "https://pwpizza.com",
      phone: "(314) 241-7799",
      image_url: "",
      verified: true,
    },
    {
      name: "Sauce on the Side",
      address: "1637 Tower Grove Ave, St. Louis, MO 63110",
      cuisine_type: "Calzones",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["eggs"],
      allergens_handled: ["gluten", "dairy"],
      description: "Gourmet calzone shop with gluten-free dough prepared in a separate area. Fillings clearly labeled for common allergens. Salads available for those avoiding gluten entirely.",
      website: "https://sauceontheside.com",
      phone: "(314) 696-8001",
      image_url: "",
      verified: true,
    },

    // ═══ TIER 3: Dietary-Friendly (35) ═══
    // ── Italian / The Hill ──
    {
      name: "Gioia's Deli",
      address: "1934 Macklind Ave, St. Louis, MO 63110",
      cuisine_type: "Italian Deli",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["fish", "shellfish"],
      allergens_handled: ["gluten", "dairy"],
      description: "James Beard award-winning deli on The Hill. Famous hot salami sandwiches. Gluten-free bread available upon request — shared prep surfaces. Best for mild sensitivities.",
      website: "https://gioiasdeli.com",
      phone: "(314) 776-9410",
      image_url: "",
      verified: true,
    },
    {
      name: "Cunetto House of Pasta",
      address: "5453 Magnolia Ave, St. Louis, MO 63139",
      cuisine_type: "Italian",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Institution on The Hill since 1972. Gluten-free pasta available but cooked in shared water. Classic red-sauce Italian — heavy on wheat and dairy throughout the kitchen.",
      website: "https://cunetto.com",
      phone: "(314) 781-1135",
      image_url: "",
      verified: true,
    },
    {
      name: "Zia's on the Hill",
      address: "5256 Wilson Ave, St. Louis, MO 63110",
      cuisine_type: "Italian",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["fish", "shellfish"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "The Hill staple for Italian comfort food. Gluten-free pasta available but prepared in a wheat-heavy kitchen. Gluten-free salad dressings available — ask your server.",
      website: "https://ziasonthehill.com",
      phone: "(314) 776-0020",
      image_url: "",
      verified: true,
    },
    {
      name: "Charlie Gitto's on the Hill",
      address: "5226 Shaw Ave, St. Louis, MO 63110",
      cuisine_type: "Italian Fine Dining",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["fish", "shellfish"],
      allergens_handled: ["gluten", "dairy", "shellfish"],
      description: "Upscale Italian with toasted ravioli fame. Staff is knowledgeable about menu ingredients. Can modify many dishes for gluten and dairy concerns — discuss needs when ordering.",
      website: "https://charlesgittos.com",
      phone: "(314) 772-8898",
      image_url: "",
      verified: true,
    },

    // ── BBQ ──
    {
      name: "Pappy's Smokehouse",
      address: "3106 Olive St, St. Louis, MO 63103",
      cuisine_type: "Memphis-Style BBQ",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["fish", "shellfish"],
      allergens_handled: ["gluten", "dairy"],
      description: "St. Louis's most famous BBQ. Meats are smoked without gluten-containing ingredients. Most rubs are gluten-free. Sides vary — check for flour thickeners. High-volume kitchen.",
      website: "https://pappyssmokehouse.com",
      phone: "(314) 535-4340",
      image_url: "",
      verified: true,
    },
    {
      name: "Bogart's Smokehouse",
      address: "1627 S 9th St, St. Louis, MO 63104",
      cuisine_type: "St. Louis BBQ",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["fish"],
      allergens_handled: ["gluten", "dairy"],
      description: "Soulard BBQ joint with legendary ribs and burnt ends. Meats are naturally gluten-free. Sauces and sides vary — ask about ingredients. Cross-contamination possible in shared kitchen.",
      website: "https://bogartssmokehouse.com",
      phone: "(314) 621-9007",
      image_url: "",
      verified: true,
    },
    {
      name: "Sugarfire Smoke House",
      address: "605 Washington Ave, St. Louis, MO 63101",
      cuisine_type: "BBQ",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "soy"],
      description: "Downtown BBQ with creative specials. Most smoked meats are gluten-free. Sides and sauces change frequently — ask staff for current allergen info. Several St. Louis locations.",
      website: "https://sugarfiresmokehouse.com",
      phone: "(314) 394-2555",
      image_url: "",
      verified: true,
    },
    {
      name: "Salt + Smoke",
      address: "6525 Delmar Blvd, University City, MO 63130",
      cuisine_type: "Southern BBQ",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy"],
      description: "Delmar Loop BBQ with extensive bourbon list. Meats smoked without gluten. Gluten-free buns and sides available on request. Shared fryer for fries — ask about dedicated options.",
      website: "https://saltandsmokestl.com",
      phone: "(314) 727-0200",
      image_url: "",
      verified: true,
    },
    {
      name: "Beast Craft BBQ",
      address: "20 S Belt W, Belleville, IL 62220",
      cuisine_type: "Craft BBQ",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy"],
      description: "Metro-east favorite worth the drive. Award-winning pork steak and brisket. Most meats are gluten-free. Gluten-free sides clearly marked on the menu board.",
      website: "https://beastcraftbbq.com",
      phone: "(618) 257-9001",
      image_url: "",
      verified: true,
    },

    // ── Asian ──
    {
      name: "Corner 17",
      address: "6623 Delmar Blvd, University City, MO 63130",
      cuisine_type: "Chinese Hand-Pulled Noodles",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "soy", "shellfish"],
      description: "Delmar Loop spot famous for hand-pulled noodles made in a visible kitchen. Gluten-free rice noodle substitutions available. Soy sauce widely used — bring your own tamari for celiac needs.",
      website: "https://corner17.com",
      phone: "(314) 833-5533",
      image_url: "",
      verified: true,
    },
    {
      name: "Nippon Tei",
      address: "14025 Manchester Rd, Ballwin, MO 63011",
      cuisine_type: "Japanese Sushi",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "soy", "shellfish", "fish"],
      description: "Highly regarded sushi restaurant in West County. Gluten-free tamari available. Staff is trained on allergens and can guide safe choices. Notify about allergies when making a reservation.",
      website: "https://nippontei.com",
      phone: "(636) 527-0888",
      image_url: "",
      verified: true,
    },
    {
      name: "Mai Lee",
      address: "8396 Musick Memorial Dr, Brentwood, MO 63144",
      cuisine_type: "Vietnamese",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["dairy"],
      allergens_handled: ["gluten", "soy", "shellfish", "peanuts"],
      description: "St. Louis institution for Vietnamese cuisine. Many dishes are naturally gluten-free with rice noodles. Fish sauce and soy widely used — discuss allergies with your server.",
      website: "https://maileestl.com",
      phone: "(314) 989-8800",
      image_url: "",
      verified: true,
    },
    {
      name: "King & I",
      address: "3155 S Grand Blvd, St. Louis, MO 63118",
      cuisine_type: "Thai",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "soy", "shellfish", "peanuts"],
      description: "South Grand Thai favorite. Many curries are naturally gluten-free. Gluten-free soy sauce available on request. Peanuts heavily used in the kitchen — not suitable for peanut allergies.",
      website: "https://kingandistl.com",
      phone: "(314) 771-1777",
      image_url: "",
      verified: true,
    },
    {
      name: "Fork & Stix",
      address: "549 Rosedale Ave, St. Louis, MO 63112",
      cuisine_type: "Northern Thai",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["dairy"],
      allergens_handled: ["gluten", "soy", "shellfish"],
      description: "Cozy Skinker-DeBaliviere spot for Northern Thai cuisine. Many dishes use rice noodles and are naturally gluten-free. Staff can identify gluten-containing dishes on request.",
      website: "https://forkandstix.com",
      phone: "(314) 863-3945",
      image_url: "",
      verified: true,
    },

    // ── American & Burgers ──
    {
      name: "Blueberry Hill",
      address: "6504 Delmar Blvd, University City, MO 63130",
      cuisine_type: "American Diner",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Iconic Delmar Loop restaurant and music venue. Gluten-free buns available for burgers. Extensive menu with clearly marked vegetarian items. Shared fryer — avoid fried foods for celiac needs.",
      website: "https://blueberryhill.com",
      phone: "(314) 727-4444",
      image_url: "",
      verified: true,
    },
    {
      name: "Bailey's Range",
      address: "920 Olive St, St. Louis, MO 63101",
      cuisine_type: "Burgers & Shakes",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy"],
      description: "Downtown burger joint with house-made everything. Gluten-free buns available. Fries are cooked in a shared fryer. Dairy-free shakes available with coconut milk ice cream.",
      website: "https://baileysrange.com",
      phone: "(314) 241-2000",
      image_url: "",
      verified: true,
    },
    {
      name: "Hi-Pointe Drive-In",
      address: "1033 McCausland Ave, St. Louis, MO 63117",
      cuisine_type: "Burgers",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy"],
      description: "Retro burger joint near The Hill. Gluten-free buns available. All food prepared in a shared kitchen with wheat flour widely used. Best for mild to moderate sensitivities.",
      website: "https://hipointedrivein.com",
      phone: "(314) 645-3500",
      image_url: "",
      verified: true,
    },
    {
      name: "The Royale",
      address: "3132 S Kingshighway Blvd, St. Louis, MO 63139",
      cuisine_type: "American Gastropub",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["shellfish"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Tower Grove South gastropub with a great patio. Vegetarian and gluten-free options clearly marked. Staff can advise on modifications. Kitchen is small — best for moderate sensitivities.",
      website: "https://theroyale.com",
      phone: "(314) 772-3600",
      image_url: "",
      verified: true,
    },
    {
      name: "Olive + Oak",
      address: "216 W Lockwood Ave, Webster Groves, MO 63119",
      cuisine_type: "New American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["shellfish"],
      allergens_handled: ["gluten", "dairy", "nuts", "shellfish"],
      description: "Acclaimed Webster Groves restaurant from the Claverach Farm team. Menu changes seasonally; staff is well-trained on all ingredients and happy to accommodate dietary needs with notice.",
      website: "https://oliveandoakstl.com",
      phone: "(314) 736-1370",
      image_url: "",
      verified: true,
    },
    {
      name: "Sidney Street Cafe",
      address: "2000 Sidney St, St. Louis, MO 63104",
      cuisine_type: "American Fine Dining",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "nuts", "shellfish"],
      description: "Intimate Benton Park fine dining destination. Chef Kevin Nashan accommodates dietary restrictions with advance notice. Tasting menu can be adapted for most allergies.",
      website: "https://sidneystreetcafe.com",
      phone: "(314) 771-5777",
      image_url: "",
      verified: true,
    },
    {
      name: "Farmhaus",
      address: "3257 Ivanhoe Ave, St. Louis, MO 63139",
      cuisine_type: "Farm-to-Table American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "nuts", "eggs"],
      description: "Cozy Lindenwood Park farm-to-table. Menu changes daily based on seasonal availability. Staff knowledgeable about all ingredients; dietary needs accommodated with advance notice.",
      website: "https://farmhausrestaurant.com",
      phone: "(314) 647-3800",
      image_url: "",
      verified: true,
    },
    {
      name: "Union Loafers",
      address: "1629 Tower Grove Ave, St. Louis, MO 63110",
      cuisine_type: "Bakery & Pizza",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy"],
      description: "Botanical Heights bread bakery and pizza spot. Excellent sandwiches on house-made bread. Not suitable for gluten allergies — flour is airborne throughout. Salads available.",
      website: "https://unionloafers.com",
      phone: "(314) 833-5511",
      image_url: "",
      verified: true,
    },

    // ── Dessert & More ──
    {
      name: "Ted Drewes Frozen Custard",
      address: "6726 Chippewa St, St. Louis, MO 63109",
      cuisine_type: "Frozen Custard",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["dairy", "eggs", "gluten"],
      description: "Iconic Route 66 frozen custard stand since 1929. Custard contains dairy and eggs. Cones contain gluten — ask for a cup. Toppings vary in allergen content.",
      website: "https://teddrewes.com",
      phone: "(314) 481-2652",
      image_url: "",
      verified: true,
    },
    {
      name: "Clementine's Naughty & Nice Creamery",
      address: "1637 S 18th St, St. Louis, MO 63104",
      cuisine_type: "Ice Cream",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["fish", "shellfish"],
      allergens_handled: ["dairy", "gluten", "nuts", "eggs"],
      description: "Small-batch ice cream with boozy and classic flavors. Dairy-free and vegan options available. Allergen labels on each flavor. Gluten-free and dairy-free waffle cones on request.",
      website: "https://clementinescreamery.com",
      phone: "(314) 648-2445",
      image_url: "",
      verified: true,
    },
    {
      name: "Southwest Diner",
      address: "6803 Southwest Ave, St. Louis, MO 63143",
      cuisine_type: "Southwestern Diner",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Maplewood diner serving New Mexican-inspired breakfast and lunch. Gluten-free toast and corn tortillas available. Busy open kitchen — best for mild to moderate sensitivities.",
      website: "https://southwestdinerstl.com",
      phone: "(314) 736-5886",
      image_url: "",
      verified: true,
    },
    {
      name: "Rooster",
      address: "1104 Locust St, St. Louis, MO 63101",
      cuisine_type: "Brunch & Crepes",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Downtown brunch spot famous for crepes. Gluten-free crepe batter available. Kitchen handles wheat flour extensively — cross-contamination risk for celiac diners.",
      website: "https://roosterstl.com",
      phone: "(314) 241-8118",
      image_url: "",
      verified: true,
    },
    {
      name: "Broadway Oyster Bar",
      address: "736 S Broadway, St. Louis, MO 63102",
      cuisine_type: "Cajun & Seafood",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["shellfish", "gluten", "dairy", "fish"],
      description: "Iconic live music venue and Cajun restaurant near Busch Stadium. Seafood-heavy menu — not suitable for shellfish allergies. Gluten-free options limited; ask server for safe choices.",
      website: "https://broadwayoysterbar.com",
      phone: "(314) 621-8811",
      image_url: "",
      verified: true,
    },
    {
      name: "Grace Meat + Three",
      address: "4270 Manchester Ave, St. Louis, MO 63110",
      cuisine_type: "Southern Comfort",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "The Grove's Southern comfort spot. Fried chicken is the star — kitchen uses wheat flour extensively. Gluten-free sides available; best for mild sensitivities only.",
      website: "https://gracemeatandthree.com",
      phone: "(314) 833-3350",
      image_url: "",
      verified: true,
    },
    {
      name: "Peno Soul Food",
      address: "7600 Wydown Blvd, Clayton, MO 63105",
      cuisine_type: "Italian-Southern Fusion",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["peanuts", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Chef-owner Peno's unique Italian-meets-Southern comfort food. Many dishes are naturally gluten-free. Kitchen handles wheat — discuss needs with the chef directly.",
      website: "https://penostl.com",
      phone: "(314) 555-0305",
      image_url: "",
      verified: true,
    },
    {
      name: "Chris' at the Docket",
      address: "100 N Tucker Blvd, St. Louis, MO 63101",
      cuisine_type: "American Diner",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten", "dairy"],
      description: "Downtown lunch counter beloved by courthouse workers. Classic sandwiches and soups. Gluten-free bread available. Small kitchen — best for mild dietary preferences.",
      website: "https://chrisatthedocket.com",
      phone: "(314) 555-0306",
      image_url: "",
      verified: true,
    },
    {
      name: "Cafe Natasha's",
      address: "3200 S Grand Blvd, St. Louis, MO 63118",
      cuisine_type: "Persian",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["fish", "shellfish"],
      allergens_handled: ["gluten", "dairy", "nuts"],
      description: "South Grand Persian gem with family recipes. Many rice-based dishes are naturally gluten-free. Nuts and dairy used in many dishes — check with staff about specific concerns.",
      website: "https://cafenatashas.com",
      phone: "(314) 696-0099",
      image_url: "",
      verified: true,
    },
  ];
}
