import type { RestaurantSeed } from "./restaurants";

// ── Nashville restaurant data (13 restaurants) ───────────────────────────────

export function getNashvilleRestaurants(): RestaurantSeed[] {
  return [
    // ═══ TIER 1: 100% Dedicated Facilities (2) ═══
    {
      name: "Sunflower Cafe",
      address: "2834 Azalea Pl, Nashville, TN 37204",
      cuisine_type: "Vegan & Gluten-Free",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "fish", "gluten", "peanuts", "sesame", "shellfish", "tree nuts"],
      allergens_handled: ["gluten", "soy", "nuts"],
      description: "Berry Hill's dedicated vegan cafe with a 100% plant-based kitchen. No dairy or eggs on premises. Extensive gluten-free options with dedicated fryer. Celiac-aware staff and separate GF prep areas.",
      website: "https://sunflowercafenashville.com",
      phone: "(615) 730-8105",
      image_url: "",
      verified: true,
    },
    {
      name: "The BE-Hive",
      address: "2414 Gallatin Ave, Nashville, TN 37206",
      cuisine_type: "Vegan Deli & Market",
      safety_tier: 1,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "fish", "gluten", "peanuts", "sesame", "tree nuts"],
      allergens_handled: ["gluten", "soy", "nuts"],
      description: "East Nashville's 100% plant-based deli and market. All foods are dairy-free and egg-free. Seitan sandwiches, salads, and grab-and-go items. Gluten-free options clearly marked.",
      website: "https://thebehive.com",
      phone: "(615) 649-8150",
      image_url: "",
      verified: true,
    },

    // ═══ TIER 2: Certified Allergen Protocols (4) ═══
    {
      name: "True Food Kitchen",
      address: "3996 Hillsboro Pike, Nashville, TN 37215",
      cuisine_type: "Health-Conscious American",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten", "peanuts", "shellfish"],
      allergens_handled: ["gluten", "dairy", "soy", "peanuts", "tree nuts", "shellfish"],
      description: "Green Hills location of the seasonal health-driven restaurant. Detailed allergen matrix available; all staff trained on major food allergens and cross-contact prevention protocols.",
      website: "https://truefoodkitchen.com",
      phone: "(615) 488-3195",
      image_url: "",
      verified: true,
    },
    {
      name: "Avo",
      address: "3 City Ave, Nashville, TN 37209",
      cuisine_type: "Vegan & Health-Conscious",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten", "peanuts", "shellfish"],
      allergens_handled: ["gluten", "soy", "nuts"],
      description: "The Nations neighborhood vegan restaurant with a dedicated gluten-free fryer. 100% plant-based kitchen (no dairy or eggs). Clear allergen labeling and staff trained on gluten-free protocol.",
      website: "https://eatavo.com",
      phone: "(615) 329-2377",
      image_url: "",
      verified: true,
    },
    {
      name: "Butcher & Bee",
      address: "902 Main St, Nashville, TN 37206",
      cuisine_type: "Mediterranean Small Plates",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "soy", "peanuts"],
      allergens_handled: ["gluten", "dairy", "nuts", "eggs", "shellfish"],
      description: "East Nashville's Mediterranean-inspired kitchen with strong allergen protocols. Menu clearly marks gluten-free, dairy-free, and nut-free items. Staff is well-versed in dietary accommodation.",
      website: "https://butcherandbee.com",
      phone: "(615) 226-3322",
      image_url: "",
      verified: true,
    },
    {
      name: "Graze",
      address: "1888 Eastland Ave, Nashville, TN 37206",
      cuisine_type: "Vegan & Plant-Based",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "gluten", "tree nuts"],
      allergens_handled: ["gluten", "soy", "nuts"],
      description: "East Nashville's plant-based gastropub with a dedicated gluten-free fryer. All food is dairy-free and egg-free. Gluten-free options available for most menu items with separate prep.",
      website: "https://grazefoodco.com",
      phone: "(615) 686-1065",
      image_url: "",
      verified: true,
    },

    // ═══ TIER 3: Dietary-Friendly (7) ═══
    {
      name: "Hattie B's Hot Chicken",
      address: "112 19th Ave S, Nashville, TN 37203",
      cuisine_type: "Hot Chicken",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["dairy", "eggs", "gluten", "soy", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Nashville's iconic hot chicken spot. All chicken is breaded with wheat flour and fried in shared oil. Gluten-free options extremely limited — best for dairy or egg sensitivities only.",
      website: "https://hattieb.com",
      phone: "(615) 678-9393",
      image_url: "",
      verified: true,
    },
    {
      name: "Prince's Hot Chicken",
      address: "5814 Nolensville Pike, Nashville, TN 37211",
      cuisine_type: "Hot Chicken",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["dairy", "eggs", "tree nuts"],
      allergens_handled: ["gluten", "dairy"],
      description: "The original Nashville hot chicken — open since the 1930s. All chicken is flour-breaded and fried in shared oil. No gluten-free options available for the signature dish.",
      website: "https://princeshotchicken.com",
      phone: "(615) 810-9388",
      image_url: "",
      verified: true,
    },
    {
      name: "Loveless Cafe",
      address: "8400 TN-100, Nashville, TN 37221",
      cuisine_type: "Southern Comfort",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "soy"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Iconic Southern cooking destination famous for biscuits and fried chicken. Gluten-free options limited; most dishes use wheat flour. Kitchen can accommodate some dairy concerns.",
      website: "https://lovelesscafe.com",
      phone: "(615) 646-9700",
      image_url: "",
      verified: true,
    },
    {
      name: "The Pharmacy Burger Parlor",
      address: "731 McFerrin Ave, Nashville, TN 37206",
      cuisine_type: "Burgers & Beer Garden",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "soy"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "East Nashville's beer garden burger joint. Gluten-free buns available upon request. Fries are cooked in shared fryers. Best for mild sensitivities — inform staff of allergies.",
      website: "https://thepharmacynashville.com",
      phone: "(615) 712-9517",
      image_url: "",
      verified: true,
    },
    {
      name: "Martin's Bar-B-Que Joint",
      address: "410 4th Ave S, Nashville, TN 37201",
      cuisine_type: "BBQ",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "soy"],
      allergens_handled: ["gluten", "dairy"],
      description: "Whole-hog BBQ institution in downtown Nashville. Most smoked meats are naturally gluten-free. Sides vary — ask about flour-based thickeners. High-volume kitchen with shared surfaces.",
      website: "https://martinsbbqjoint.com",
      phone: "(615) 288-0880",
      image_url: "",
      verified: true,
    },
    {
      name: "Biscuit Love",
      address: "316 11th Ave S, Nashville, TN 37203",
      cuisine_type: "Southern Brunch",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["shellfish", "fish"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Gulch neighborhood brunch spot famous for bonuts and biscuit dishes. Core concept is wheat-based — gluten-free options very limited. Best for dairy or egg sensitivities.",
      website: "https://biscuitlove.com",
      phone: "(615) 490-9584",
      image_url: "",
      verified: true,
    },
    {
      name: "Rolf and Daughters",
      address: "700 Taylor St, Nashville, TN 37208",
      cuisine_type: "New American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "shellfish"],
      allergens_handled: ["gluten", "dairy", "nuts", "eggs"],
      description: "Germantown neighborhood restaurant with house-made pasta and seasonal plates. Staff is knowledgeable about allergens; kitchen can modify most dishes. Gluten-free pasta available on request.",
      website: "https://rolfanddaughters.com",
      phone: "(615) 866-9897",
      image_url: "",
      verified: true,
    },

    // ═══ AUTO-DISCOVERED (Tier 2-3 via Google Places) ═══
{
      name: "The Finch",
      address: "111 10th Ave S #310, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Hampton Social - Nashville",
      address: "201 1st Ave S, Nashville, TN 37201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Harper's",
      address: "2 Lea Ave, Nashville, TN 37210",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Butter Milk Ranch",
      address: "2407 12th Ave S, Nashville, TN 37204",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Harriet's Rooftop",
      address: "710 Demonbreun St 19th Floor, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Puckett's Restaurant",
      address: "500 Church St, Nashville, TN 37219",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Stillery",
      address: "113 2nd Ave N, Nashville, TN 37201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Monell's",
      address: "1235 6th Ave N, Nashville, TN 37208",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Lockeland Table",
      address: "1520 Woodland St, Nashville, TN 37206",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Milk & Honey Gulch",
      address: "214 11th Ave S, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "417 Union",
      address: "417 Union St, Nashville, TN 37219",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Treehouse Nashville",
      address: "1011 Clearview Ave, Nashville, TN 37206",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Aba Nashville",
      address: "435 Houston St, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Jeff Ruby's Steakhouse",
      address: "300 4th Ave N, Nashville, TN 37219",
      cuisine_type: "Steakhouse",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","eggs"],
      description: "Auto-discovered via Google Places. A steakhouse restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Two Hands",
      address: "606 8th Ave S, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Loveless Cafe",
      address: "8400 TN-100, Nashville, TN 37221",
      cuisine_type: "Cafe",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A cafe restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Gathre",
      address: "1810 Broadway, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Assembly Food Hall",
      address: "5055 Broadway, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Twelve Thirty Club",
      address: "550 Broadway, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Old Mill Restaurant",
      address: "164 Old Mill Ave, Pigeon Forge, TN 37863",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Iberian Pig",
      address: "607 Overton St, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Standard",
      address: "167 Rosa L Parks Blvd, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Fifth + Broadway",
      address: "5036 Broadway, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Skull's Rainbow Room",
      address: "222 Printers Alley, Nashville, TN 37219",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Noko",
      address: "701 Porter Rd, Nashville, TN 37206",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Aquarium Restaurant",
      address: "516 Opry Mills Dr, Nashville, TN 37214",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Boqueria Fifth + Broadway",
      address: "5005 Broadway, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "etch",
      address: "303 Demonbreun St, Nashville, TN 37201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Husk Nashville",
      address: "37 Rutledge St, Nashville, TN 37210",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Bastion",
      address: "434 Houston St Ste 110, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Farm House",
      address: "210 Almond St, Nashville, TN 37201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Miranda Lambert's Casa Rosa",
      address: "308 Broadway, Nashville, TN 37201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Sixty Vines",
      address: "5055 Broadway Suite 3200, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "STK Steakhouse",
      address: "700 12th Ave S, Nashville, TN 37203",
      cuisine_type: "Steakhouse",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","eggs"],
      description: "Auto-discovered via Google Places. A steakhouse restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Kayne Prime",
      address: "1103 McGavock St, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Luogo",
      address: "211 12th Ave S, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Adele's",
      address: "1210 McGavock St, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Hattie B's Hot Chicken - Nashville - Midtown",
      address: "112 19th Ave S, Nashville, TN 37203",
      cuisine_type: "Fried Chicken",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A fried chicken restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Pelato - Nashville",
      address: "1300 3rd Ave N, Nashville, TN 37208",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Darfons Restaurant + Bar",
      address: "2810 Elm Hill Pike, Nashville, TN 37214",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Jason Aldean's Kitchen + Rooftop Bar",
      address: "307 Broadway, Nashville, TN 37201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Mockingbird",
      address: "121 12th Ave N, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Luke's 32 Bridge",
      address: "301 Broadway, Nashville, TN 37201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Ole Red",
      address: "300 Broadway, Nashville, TN 37201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Rippy's Honky Tonk",
      address: "429 Broadway, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Nashville Grange",
      address: "1000 Broadway, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "House of Cards",
      address: "Lower Level, 119 3rd Ave S, Nashville, TN 37201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Pinewood",
      address: "33 Peabody St, Nashville, TN 37210",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Tootsies Orchid Lounge",
      address: "422 Broadway, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "NashHouse Southern Spoon and Saloon",
      address: "114 8th Ave S, Nashville, TN 37203",
      cuisine_type: "Southern",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A southern restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Lookout at Ole Red",
      address: "300 Broadway, Nashville, TN 37201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Robert's Western World",
      address: "416 Broadway # B, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Midtown Cafe",
      address: "102 19th Ave S, Nashville, TN 37203",
      cuisine_type: "Cafe",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A cafe restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Friends in Low Places Bar & Honky-Tonk",
      address: "411 Broadway, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Diner Nashville",
      address: "200 3rd Ave S, Nashville, TN 37201",
      cuisine_type: "American Diner",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american diner restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Frothy Monkey",
      address: "235 Rep. John Lewis Way N, Nashville, TN 37219",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Gray & Dudley",
      address: "222 3rd Ave N, Nashville, TN 37201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Gannons Nashville",
      address: "170 4th Ave N, Nashville, TN 37219",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Library Restaurant & Lounge",
      address: "623 Union St First Floor, Nashville, TN 37219",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Another Broken Egg Cafe",
      address: "208 Commerce St, Nashville, TN 37201",
      cuisine_type: "Cafe",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A cafe restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Bungalow 10 Dining",
      address: "1910 Belcourt Ave, Nashville, TN 37212",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "1 Kitchen",
      address: "710 Demonbreun St, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Bourbon Steak by Michael Mina",
      address: "201 8th Ave S 34th floor, Nashville, TN 37203",
      cuisine_type: "Steakhouse",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","eggs"],
      description: "Auto-discovered via Google Places. A steakhouse restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Alla Vita Nashville",
      address: "523 Houston St, Nashville, TN 37203",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Nashville. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
  ];
}
