import type { RestaurantSeed } from "./restaurants";

// ── Dallas restaurant data (14 restaurants) ──────────────────────────────────

export function getDallasRestaurants(): RestaurantSeed[] {
  return [
    // ═══ TIER 1: 100% Dedicated Facilities (2) ═══
    {
      name: "Company Cafe",
      address: "2104 Greenville Ave, Dallas, TX 75206",
      cuisine_type: "Gluten-Free American",
      safety_tier: 1,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "peanuts", "shellfish", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "soy", "eggs"],
      description: "Lower Greenville's dedicated gluten-free kitchen serving comfort food classics. Fried chicken, chicken-fried steak, and pancakes — all 100% celiac-safe with dedicated fryers and prep areas.",
      website: "https://companycafe.com",
      phone: "(214) 827-2233",
      image_url: "",
      verified: true,
    },
    {
      name: "Unrefined Bakery",
      address: "3411 Preston Rd, Frisco, TX 75034",
      cuisine_type: "Gluten-Free & Vegan Bakery",
      safety_tier: 1,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "fish", "gluten", "peanuts", "sesame", "shellfish", "soy", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "soy", "eggs", "nuts"],
      description: "DFW's dedicated gluten-free, soy-free, and preservative-free bakery. Cakes, cookies, breads, and custom orders — all in a 100% gluten-free facility with dairy-free and vegan options.",
      website: "https://unrefinedbakery.com",
      phone: "(972) 292-7400",
      image_url: "",
      verified: true,
    },

    // ═══ TIER 2: Certified Allergen Protocols (4) ═══
    {
      name: "True Food Kitchen",
      address: "8383 Preston Center Plaza, Dallas, TX 75225",
      cuisine_type: "Health-Conscious American",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "fish", "gluten", "sesame", "soy", "peanuts"],
      allergens_handled: ["gluten", "dairy", "soy", "peanuts", "tree nuts", "shellfish"],
      description: "Preston Center location of the seasonal health-driven restaurant. Detailed allergen matrix, trained staff on all major allergens, and separate prep areas for allergen-sensitive dishes.",
      website: "https://truefoodkitchen.com",
      phone: "(469) 804-6820",
      image_url: "",
      verified: true,
    },
    {
      name: "HG Sply Co.",
      address: "2008 Greenville Ave, Dallas, TX 75206",
      cuisine_type: "Paleo-Inspired American",
      safety_tier: 2,
      has_dedicated_fryer: true,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "peanuts", "eggs"],
      allergens_handled: ["gluten", "dairy", "soy", "peanuts", "eggs"],
      description: "Lower Greenville's paleo-inspired rooftop restaurant with dedicated gluten-free fryers. Menu clearly marks gluten-free, dairy-free, and Whole30-compliant items. Staff trained on cross-contact prevention.",
      website: "https://hgsplyco.com",
      phone: "(469) 334-0896",
      image_url: "",
      verified: true,
    },
    {
      name: "Flower Child",
      address: "5450 W Lovers Ln, Dallas, TX 75209",
      cuisine_type: "Health-Conscious Bowls",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["gluten", "dairy", "peanuts", "eggs"],
      allergens_handled: ["gluten", "dairy", "soy", "peanuts", "tree nuts", "eggs"],
      description: "Inwood Village location of the fast-casual healthy eatery. Extensive gluten-free, dairy-free, and vegan options clearly labeled. Separate prep zones for allergen-sensitive dishes.",
      website: "https://iamaflowerchild.com",
      phone: "(214) 242-1964",
      image_url: "",
      verified: true,
    },
    {
      name: "Modern Market Eatery",
      address: "5925 Forest Ln, Dallas, TX 75230",
      cuisine_type: "Health-Conscious Fast Casual",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: true,
      allergen_trained_staff: true,
      free_from: ["dairy", "gluten", "tree nuts", "eggs"],
      allergens_handled: ["gluten", "dairy", "soy", "eggs", "nuts"],
      description: "Fast-casual spot with digital allergen and nutrition filtering. Gluten-free pizza crust and bread available with separate prep. Whole30, vegan, and paleo options clearly marked.",
      website: "https://modernmarket.com",
      phone: "(972) 803-4380",
      image_url: "",
      verified: true,
    },

    // ═══ TIER 3: Dietary-Friendly (8) ═══
    {
      name: "Pecan Lodge",
      address: "2702 Main St, Dallas, TX 75226",
      cuisine_type: "Texas BBQ",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "tree nuts"],
      allergens_handled: ["gluten"],
      description: "Deep Ellum's award-winning BBQ destination. Most smoked meats are naturally gluten-free (no sauce on the meat). High-volume pit — cross-contamination possible. Ask about rub ingredients.",
      website: "https://pecanlodge.com",
      phone: "(214) 748-8900",
      image_url: "",
      verified: true,
    },
    {
      name: "Knife Dallas",
      address: "5300 E Mockingbird Ln, Dallas, TX 75206",
      cuisine_type: "Steakhouse",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["gluten", "tree nuts"],
      allergens_handled: ["gluten", "dairy", "eggs", "nuts"],
      description: "John Tesar's acclaimed steakhouse at The Highland. High-end kitchen with well-trained staff who can navigate allergies. Steaks are naturally gluten-free; discuss modifications for sides and sauces.",
      website: "https://knifedallas.com",
      phone: "(214) 443-9339",
      image_url: "",
      verified: true,
    },
    {
      name: "Meso Maya",
      address: "1611 McKinney Ave, Dallas, TX 75202",
      cuisine_type: "Mexican & Mayan",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["dairy", "eggs", "soy"],
      allergens_handled: ["gluten", "dairy", "nuts"],
      description: "Uptown spot for authentic interior Mexican cuisine. Many dishes use corn masa and are naturally gluten-free. Allergen guide available; staff trained to assist with dietary needs.",
      website: "https://mesomaya.com",
      phone: "(214) 720-8880",
      image_url: "",
      verified: true,
    },
    {
      name: "Velvet Taco",
      address: "4622 Greenville Ave, Dallas, TX 75206",
      cuisine_type: "Creative Tacos",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "soy"],
      allergens_handled: ["gluten", "dairy", "soy", "eggs"],
      description: "Late-night taco spot with globally-inspired flavors. Corn tortillas available for most tacos; gluten-free items noted on the menu. Shared kitchen — best for mild-to-moderate sensitivities.",
      website: "https://velvettaco.com",
      phone: "(214) 919-1861",
      image_url: "",
      verified: true,
    },
    {
      name: "Lockhart Smokehouse",
      address: "400 W Davis St, Dallas, TX 75208",
      cuisine_type: "Texas BBQ",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "soy"],
      allergens_handled: ["gluten"],
      description: "Bishop Arts District BBQ joint serving Central Texas-style smoked meats. Meats are gluten-free; sausage may contain fillers. Shared prep surfaces — ask about cross-contamination risk.",
      website: "https://lockhartsmokehouse.com",
      phone: "(214) 944-5521",
      image_url: "",
      verified: true,
    },
    {
      name: "Mi Cocina",
      address: "3699 McKinney Ave, Dallas, TX 75204",
      cuisine_type: "Tex-Mex",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "shellfish"],
      allergens_handled: ["gluten", "dairy"],
      description: "Dallas-born Tex-Mex chain with classic margaritas and fajitas. Corn tortillas and gluten-free options available on request. Busy kitchen — best for mild sensitivities or dairy concerns.",
      website: "https://micocina.com",
      phone: "(214) 526-6426",
      image_url: "",
      verified: true,
    },
    {
      name: "The French Room",
      address: "1321 Commerce St, Dallas, TX 75202",
      cuisine_type: "French Fine Dining",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: true,
      free_from: ["dairy", "shellfish"],
      allergens_handled: ["gluten", "dairy", "nuts", "eggs", "shellfish"],
      description: "Historic fine dining in The Adolphus hotel. World-class kitchen with exceptional allergen awareness. Notify of dietary restrictions when making reservations for the best experience.",
      website: "https://theadolphus.com",
      phone: "(214) 742-8200",
      image_url: "",
      verified: true,
    },
    {
      name: "Rodeo Goat",
      address: "1926 Market Center Blvd, Dallas, TX 75207",
      cuisine_type: "Burgers",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten", "shellfish"],
      allergens_handled: ["gluten", "dairy", "eggs"],
      description: "Design District burger joint with creative patties and a lively patio. Gluten-free buns available. Fries cooked in shared oil — not suitable for severe gluten allergies.",
      website: "https://rodeogoat.com",
      phone: "(214) 741-4628",
      image_url: "",
      verified: true,
    },

    // ═══ AUTO-DISCOVERED (Tier 2-3 via Google Places) ═══
{
      name: "The Henry",
      address: "2301 N Akard St Ste 250, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Woolworth",
      address: "1520 Elm St #201, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Dragonfly",
      address: "2332 Leonard St, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Hampton Social - Dallas",
      address: "1520 Main St, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Terry Black's Barbecue",
      address: "3025 Main St, Dallas, TX 75226",
      cuisine_type: "BBQ",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy","eggs"],
      description: "Auto-discovered via Google Places. A bbq restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Exchange Food Hall",
      address: "211 S Akard St, Dallas, TX 75202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "3Eleven Kitchen and Cocktails",
      address: "311 N Market St #100, Dallas, TX 75202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Monarch Restaurant",
      address: "1401 Elm St 49th Floor, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Little Daisy",
      address: "1401 Elm St, Dallas, TX 75202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "MIRADOR",
      address: "1608 Elm St, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Crown Block Dallas",
      address: "300 Reunion Blvd E, Dallas, TX 75207",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Written by the Seasons",
      address: "380 Melba St, Dallas, TX 75208",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "La Stella Cucina Verace",
      address: "2330 Flora St #150, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Kitchen + Kocktails",
      address: "1933 Elm St, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Y.O. Ranch Steakhouse",
      address: "702 Ross Ave, Dallas, TX 75202",
      cuisine_type: "Steakhouse",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","eggs"],
      description: "Auto-discovered via Google Places. A steakhouse restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Mansion Restaurant",
      address: "2821 Turtle Creek Blvd, Dallas, TX 75219",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "STK Steakhouse",
      address: "2000 McKinney Ave, Dallas, TX 75201",
      cuisine_type: "Steakhouse",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","eggs"],
      description: "Auto-discovered via Google Places. A steakhouse restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Chet's Dallas",
      address: "208 N Market St, Dallas, TX 75202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Rodeo Bar",
      address: "1321 Commerce St, Dallas, TX 75202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Perry's Steakhouse & Grille",
      address: "2100 Olive St Ste 100, Dallas, TX 75201",
      cuisine_type: "Steakhouse",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","eggs"],
      description: "Auto-discovered via Google Places. A steakhouse restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Haywire",
      address: "1920 McKinney Ave Ste 100, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Sixty Vines Dallas",
      address: "500 Crescent Ct Ste 160, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Texas Spice",
      address: "555 S Lamar St, Dallas, TX 75202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Billy Can Can",
      address: "2386 Victory Park Ln, Dallas, TX 75219",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "ASTRA Kitchen + Lounge",
      address: "1717 Leonard St, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Gemma",
      address: "2323 N Henderson Ave #109, Dallas, TX 75206",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Fearing's Restaurant",
      address: "2121 McKinney Ave, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "City Hall Bistro",
      address: "1321 Commerce St, Dallas, TX 75202",
      cuisine_type: "French",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","eggs","tree nuts"],
      description: "Auto-discovered via Google Places. A french restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Town Hearth",
      address: "1617 Market Center Blvd, Dallas, TX 75207",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Dakota's Steakhouse",
      address: "600 N Akard St, Dallas, TX 75201",
      cuisine_type: "Steakhouse",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","eggs"],
      description: "Auto-discovered via Google Places. A steakhouse restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Stillwell's",
      address: "2575 McKinnon St, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Truluck's Ocean's Finest Seafood and Crab",
      address: "2401 McKinney Ave, Dallas, TX 75201",
      cuisine_type: "Seafood",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","shellfish"],
      description: "Auto-discovered via Google Places. A seafood restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Capital Grille",
      address: "500 Crescent Ct, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Uchi Dallas",
      address: "2817 Maple Ave, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Quarter Acre",
      address: "2023 Greenville Ave #110, Dallas, TX 75206",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Hawkers Asian Street Food",
      address: "2800 Main St, Dallas, TX 75226",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy","soy","peanuts"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Rj Mexican Cuisine",
      address: "1701 N Market St #102, Dallas, TX 75202",
      cuisine_type: "Mexican",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy","soy"],
      description: "Auto-discovered via Google Places. A mexican restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Good Graces",
      address: "3033 Fairmount St, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Moxies Dallas Uptown Restaurant",
      address: "100 Crescent Ct, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Rustic",
      address: "3656 Howell St, Dallas, TX 75204",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Yardbird",
      address: "2121 N Pearl St St 170, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "HQ Dallas Rooftop",
      address: "310 S Houston St 12th floor, Dallas, TX 75202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Sky Blossom Rooftop Bistro Bar",
      address: "1514 Elm St #611, Dallas, TX 75201",
      cuisine_type: "French",
      safety_tier: 2,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten","dairy"],
      allergens_handled: ["gluten","dairy","eggs","tree nuts"],
      description: "Auto-discovered via Google Places. A french restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Bucket and Rope",
      address: "600 S Harwood St, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Culinary Dropout",
      address: "150 Turtle Creek Blvd #101, Dallas, TX 75207",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Stock & Barrel",
      address: "316 W Davis St, Dallas, TX 75208",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Uno Mas Tex Mex",
      address: "1525 Main St, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy","soy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Derby Restaurant Dallas",
      address: "9100 John W. Carpenter Fwy, Dallas, TX 75247",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Brass Ram",
      address: "2130 Commerce St 2nd Floor, Dallas, TX 75201",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Al Biernat's Oak Lawn",
      address: "4217 Oak Lawn Ave, Dallas, TX 75219",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Hudson House",
      address: "4448 Lovers Ln, Dallas, TX 75225",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "The Dallas World Aquarium",
      address: "1801 N Griffin St, Dallas, TX 75202",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
    {
      name: "Backyard - Dallas",
      address: "505 N Good Latimer Expy, Dallas, TX 75204",
      cuisine_type: "American",
      safety_tier: 3,
      has_dedicated_fryer: false,
      has_isolated_prep: false,
      allergen_trained_staff: false,
      free_from: ["gluten"],
      allergens_handled: ["gluten","dairy"],
      description: "Auto-discovered via Google Places. A american restaurant in Dallas. Contact the restaurant directly to confirm allergen protocols and kitchen practices.",
      website: "",
      phone: "",
      image_url: "",
      verified: false,
    },
  ];
}
