/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteReviewRouteImport } from './routes/write-review'
import { Route as UpdateListingRouteImport } from './routes/update-listing'
import { Route as TravelCardsRouteImport } from './routes/travel-cards'
import { Route as SubmitPostRouteImport } from './routes/submit-post'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RoutePlannerRouteImport } from './routes/route-planner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProcessRepliesRouteImport } from './routes/process-replies'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListYourVenueRouteImport } from './routes/list-your-venue'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessIndexRouteImport } from './routes/business/index'
import { Route as CityCitySlugRouteImport } from './routes/city/$citySlug'
import { Route as BusinessRegisterRouteImport } from './routes/business/register'
import { Route as BusinessDashboardRouteImport } from './routes/business/dashboard'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminRestaurantsRouteImport } from './routes/admin/restaurants'
import { Route as AdminImportEmailsRouteImport } from './routes/admin/import-emails'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as BusinessDashboardBadgesRouteImport } from './routes/business/dashboard/badges'
import { Route as BusinessDashboardAuditRouteImport } from './routes/business/dashboard/audit'

const WriteReviewRoute = WriteReviewRouteImport.update({
  id: '/write-review',
  path: '/write-review',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateListingRoute = UpdateListingRouteImport.update({
  id: '/update-listing',
  path: '/update-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelCardsRoute = TravelCardsRouteImport.update({
  id: '/travel-cards',
  path: '/travel-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitPostRoute = SubmitPostRouteImport.update({
  id: '/submit-post',
  path: '/submit-post',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutePlannerRoute = RoutePlannerRouteImport.update({
  id: '/route-planner',
  path: '/route-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRepliesRoute = ProcessRepliesRouteImport.update({
  id: '/process-replies',
  path: '/process-replies',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListYourVenueRoute = ListYourVenueRouteImport.update({
  id: '/list-your-venue',
  path: '/list-your-venue',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityCitySlugRoute = CityCitySlugRouteImport.update({
  id: '/city/$citySlug',
  path: '/city/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRegisterRoute = BusinessRegisterRouteImport.update({
  id: '/business/register',
  path: '/business/register',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDashboardRoute = BusinessDashboardRouteImport.update({
  id: '/business/dashboard',
  path: '/business/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/admin/restaurants',
  path: '/admin/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportEmailsRoute = AdminImportEmailsRouteImport.update({
  id: '/admin/import-emails',
  path: '/admin/import-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDashboardBadgesRoute = BusinessDashboardBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => BusinessDashboardRoute,
} as any)
const BusinessDashboardAuditRoute = BusinessDashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => BusinessDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claim': typeof ClaimRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/list-your-venue': typeof ListYourVenueRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/process-replies': typeof ProcessRepliesRoute
  '/profile': typeof ProfileRoute
  '/route-planner': typeof RoutePlannerRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/submit-post': typeof SubmitPostRoute
  '/travel-cards': typeof TravelCardsRoute
  '/update-listing': typeof UpdateListingRoute
  '/write-review': typeof WriteReviewRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/import-emails': typeof AdminImportEmailsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/business/dashboard': typeof BusinessDashboardRouteWithChildren
  '/business/register': typeof BusinessRegisterRoute
  '/city/$citySlug': typeof CityCitySlugRoute
  '/business/': typeof BusinessIndexRoute
  '/business/dashboard/audit': typeof BusinessDashboardAuditRoute
  '/business/dashboard/badges': typeof BusinessDashboardBadgesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claim': typeof ClaimRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/list-your-venue': typeof ListYourVenueRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/process-replies': typeof ProcessRepliesRoute
  '/profile': typeof ProfileRoute
  '/route-planner': typeof RoutePlannerRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/submit-post': typeof SubmitPostRoute
  '/travel-cards': typeof TravelCardsRoute
  '/update-listing': typeof UpdateListingRoute
  '/write-review': typeof WriteReviewRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/import-emails': typeof AdminImportEmailsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/business/dashboard': typeof BusinessDashboardRouteWithChildren
  '/business/register': typeof BusinessRegisterRoute
  '/city/$citySlug': typeof CityCitySlugRoute
  '/business': typeof BusinessIndexRoute
  '/business/dashboard/audit': typeof BusinessDashboardAuditRoute
  '/business/dashboard/badges': typeof BusinessDashboardBadgesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claim': typeof ClaimRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/list-your-venue': typeof ListYourVenueRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/process-replies': typeof ProcessRepliesRoute
  '/profile': typeof ProfileRoute
  '/route-planner': typeof RoutePlannerRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/submit-post': typeof SubmitPostRoute
  '/travel-cards': typeof TravelCardsRoute
  '/update-listing': typeof UpdateListingRoute
  '/write-review': typeof WriteReviewRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/import-emails': typeof AdminImportEmailsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/business/dashboard': typeof BusinessDashboardRouteWithChildren
  '/business/register': typeof BusinessRegisterRoute
  '/city/$citySlug': typeof CityCitySlugRoute
  '/business/': typeof BusinessIndexRoute
  '/business/dashboard/audit': typeof BusinessDashboardAuditRoute
  '/business/dashboard/badges': typeof BusinessDashboardBadgesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/claim'
    | '/dashboard'
    | '/faq'
    | '/legal'
    | '/list-your-venue'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/process-replies'
    | '/profile'
    | '/route-planner'
    | '/search'
    | '/signup'
    | '/submit-post'
    | '/travel-cards'
    | '/update-listing'
    | '/write-review'
    | '/admin/analytics'
    | '/admin/import-emails'
    | '/admin/restaurants'
    | '/blog/$slug'
    | '/business/dashboard'
    | '/business/register'
    | '/city/$citySlug'
    | '/business/'
    | '/business/dashboard/audit'
    | '/business/dashboard/badges'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/claim'
    | '/dashboard'
    | '/faq'
    | '/legal'
    | '/list-your-venue'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/process-replies'
    | '/profile'
    | '/route-planner'
    | '/search'
    | '/signup'
    | '/submit-post'
    | '/travel-cards'
    | '/update-listing'
    | '/write-review'
    | '/admin/analytics'
    | '/admin/import-emails'
    | '/admin/restaurants'
    | '/blog/$slug'
    | '/business/dashboard'
    | '/business/register'
    | '/city/$citySlug'
    | '/business'
    | '/business/dashboard/audit'
    | '/business/dashboard/badges'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/claim'
    | '/dashboard'
    | '/faq'
    | '/legal'
    | '/list-your-venue'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/process-replies'
    | '/profile'
    | '/route-planner'
    | '/search'
    | '/signup'
    | '/submit-post'
    | '/travel-cards'
    | '/update-listing'
    | '/write-review'
    | '/admin/analytics'
    | '/admin/import-emails'
    | '/admin/restaurants'
    | '/blog/$slug'
    | '/business/dashboard'
    | '/business/register'
    | '/city/$citySlug'
    | '/business/'
    | '/business/dashboard/audit'
    | '/business/dashboard/badges'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClaimRoute: typeof ClaimRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  LegalRoute: typeof LegalRoute
  ListYourVenueRoute: typeof ListYourVenueRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ProcessRepliesRoute: typeof ProcessRepliesRoute
  ProfileRoute: typeof ProfileRoute
  RoutePlannerRoute: typeof RoutePlannerRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SubmitPostRoute: typeof SubmitPostRoute
  TravelCardsRoute: typeof TravelCardsRoute
  UpdateListingRoute: typeof UpdateListingRoute
  WriteReviewRoute: typeof WriteReviewRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminImportEmailsRoute: typeof AdminImportEmailsRoute
  AdminRestaurantsRoute: typeof AdminRestaurantsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BusinessDashboardRoute: typeof BusinessDashboardRouteWithChildren
  BusinessRegisterRoute: typeof BusinessRegisterRoute
  CityCitySlugRoute: typeof CityCitySlugRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/write-review': {
      id: '/write-review'
      path: '/write-review'
      fullPath: '/write-review'
      preLoaderRoute: typeof WriteReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-listing': {
      id: '/update-listing'
      path: '/update-listing'
      fullPath: '/update-listing'
      preLoaderRoute: typeof UpdateListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-cards': {
      id: '/travel-cards'
      path: '/travel-cards'
      fullPath: '/travel-cards'
      preLoaderRoute: typeof TravelCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-post': {
      id: '/submit-post'
      path: '/submit-post'
      fullPath: '/submit-post'
      preLoaderRoute: typeof SubmitPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-planner': {
      id: '/route-planner'
      path: '/route-planner'
      fullPath: '/route-planner'
      preLoaderRoute: typeof RoutePlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process-replies': {
      id: '/process-replies'
      path: '/process-replies'
      fullPath: '/process-replies'
      preLoaderRoute: typeof ProcessRepliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-your-venue': {
      id: '/list-your-venue'
      path: '/list-your-venue'
      fullPath: '/list-your-venue'
      preLoaderRoute: typeof ListYourVenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$citySlug': {
      id: '/city/$citySlug'
      path: '/city/$citySlug'
      fullPath: '/city/$citySlug'
      preLoaderRoute: typeof CityCitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/register': {
      id: '/business/register'
      path: '/business/register'
      fullPath: '/business/register'
      preLoaderRoute: typeof BusinessRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/dashboard': {
      id: '/business/dashboard'
      path: '/business/dashboard'
      fullPath: '/business/dashboard'
      preLoaderRoute: typeof BusinessDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/admin/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import-emails': {
      id: '/admin/import-emails'
      path: '/admin/import-emails'
      fullPath: '/admin/import-emails'
      preLoaderRoute: typeof AdminImportEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/dashboard/badges': {
      id: '/business/dashboard/badges'
      path: '/badges'
      fullPath: '/business/dashboard/badges'
      preLoaderRoute: typeof BusinessDashboardBadgesRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/audit': {
      id: '/business/dashboard/audit'
      path: '/audit'
      fullPath: '/business/dashboard/audit'
      preLoaderRoute: typeof BusinessDashboardAuditRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
  }
}

interface BusinessDashboardRouteChildren {
  BusinessDashboardAuditRoute: typeof BusinessDashboardAuditRoute
  BusinessDashboardBadgesRoute: typeof BusinessDashboardBadgesRoute
}

const BusinessDashboardRouteChildren: BusinessDashboardRouteChildren = {
  BusinessDashboardAuditRoute: BusinessDashboardAuditRoute,
  BusinessDashboardBadgesRoute: BusinessDashboardBadgesRoute,
}

const BusinessDashboardRouteWithChildren =
  BusinessDashboardRoute._addFileChildren(BusinessDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClaimRoute: ClaimRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  LegalRoute: LegalRoute,
  ListYourVenueRoute: ListYourVenueRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ProcessRepliesRoute: ProcessRepliesRoute,
  ProfileRoute: ProfileRoute,
  RoutePlannerRoute: RoutePlannerRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SubmitPostRoute: SubmitPostRoute,
  TravelCardsRoute: TravelCardsRoute,
  UpdateListingRoute: UpdateListingRoute,
  WriteReviewRoute: WriteReviewRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminImportEmailsRoute: AdminImportEmailsRoute,
  AdminRestaurantsRoute: AdminRestaurantsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BusinessDashboardRoute: BusinessDashboardRouteWithChildren,
  BusinessRegisterRoute: BusinessRegisterRoute,
  CityCitySlugRoute: CityCitySlugRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
